### ISSUE TITLE
安卓uc浏览器屏幕旋转问题

### ISSUE THREAD

**Issue by YunyChan** [amfe/lib-flexible#10]
我发现，在android的UC浏览器下，如果旋转屏幕后（特别是从横屏转为竖屏），flexible的js确实已经正确执行并正确设置了根元素的font-size，但是页面的所有以rem为单位的元素尺寸并没有根据新的基准像素进行设置（重绘？），从而导致元素显示的还是原来的尺寸。

同时页面元素的样式定义方式我都尽量参照淘宝首页的样式进行设置（例如每个元素都定义了宽高和大部分都使用了box-sizing属性。）

而恰恰手机淘宝的首页却可以正确处理这种屏幕旋转问题。望能得到解答。

ps：wp的ie浏览器和uc在旋转屏幕后，有小部分特定元素也会出现上述情况。

**Comment by q165411054** [comment]
同时我发现通过css的媒体查询来定义基准像素，则能完美解决以上问题。

**Comment by udbmnm** [comment]
@q165411054 我也发现这问题了，不过我不是旋转屏幕，是直接打开就是原来尺寸，相当于放大，是安卓4.2.2默认浏览器下，我用调试工具改动一个字体大小然后改回来又好了，类似古老IE的bug，但是淘宝打开居然是好的，真是奇葩，在谷歌搜问题都不好描述。。。我直接使用css也是好的，动态改根节点字体大小就不行，只是部分机型

**Comment by leecade** [comment]
我注意到通过 js 设置根元素的 `font-size`, 在微信初次打开时(可能因为缓存或渲染优化的策略非必现), 未进行正确的渲染, 刷新后能正常

**Comment by q165411054** [comment]
@leecade 有没有试过用css的媒体查询来定义基准像素来处理？

**Comment by huboshu0819** [comment]
我也是遇到了这种情况，但是我的只时一部分没有渲染出来，而其他的显示正常。

**Comment by huboshu0819** [comment]
另外还想问一个问题，为什么要给html和body都加上fontsize？

**Comment by q165411054** [comment]
@huboshu0819 
我的理解是：
body上的设置是为了覆盖html的字号，从而让整个body内字体有一个正常的默认字号。

**Comment by dxtiger** [comment]
给html加个-webkit-text-size-adjust: 100%;

**Comment by YunyChan** [comment]
已经找到兼容方案，可通过js在页面的head里生成定义了html元素font-size的style元素来解决！
如下：
<style id="rootFontSize">html{font-size: 100px !important;}</style>

注意还加了important来提高权重

**Comment by weilejiayou** [comment]
出现问题，移动端在三星c8的时候，出现页面右移动
