### ISSUE TITLE
在很多安卓系统字体设置大小后，rem 不准了

### ISSUE THREAD

**Issue by dd1994** [amfe/lib-flexible#100]
我在一台小米 4c 系统安卓 5.1.1 ，把系统设置里把字体设大后，rem 就不准了。。我尝试了好几台安卓手机设置系统字体都是这样。。手淘的很多页面打开都乱了。。

**Comment by dd1994** [comment]
只是在 webview 里面不准，其它浏览器里面都是正常的。。

**Comment by enng0227** [comment]
js 给 html 设置一个字体大小

**Comment by airen** [comment]
如果`root`和`font-size`被运用到元素上的`px`无法整除的时候，会出现小数位，而且在浏览器内核对小数位计算还是有不同的，所以有可能有极小的偏差。另外如果人为的设置了系统默认字号，会造成页面混乱，这个坑我们也碰到了，这就好比在PC时代，使用`ctrl + `放大浏览器页面一样，如果不是使用`em`或者`%`布局，而是使用`px`布局，也会造成页面的混乱。对于如何解决这方问题，我们看看有没有相应的解决方案。

**Comment by ccsang** [comment]
这个有什么好办法吗，求指点

**Comment by dd1994** [comment]
@ccsang 手淘都乱掉了，就别考虑兼容这个问题了...
