### ISSUE TITLE
关于手淘方案的demo，CSS部分不太理解

### ISSUE THREAD

**Issue by yiranyiqing** [amfe/lib-flexible#101]
做为一名前端小白，并不能理解手淘方案中的CSS部分，可否贴出一下源码参考下，谢谢！

**Comment by airen** [comment]
@yiranyiqing 这篇文章中附有一个Demo: http://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html

这是一个简单的Demo，你可以做为参考，对于CSS部分不太理解，那就要看你对CSS了解多少了。如果你对CSS了解的不多，贴再多Demo，可能也没办法帮助你更好的理解CSS。谢谢！！
