### ISSUE TITLE
wechat里面rem应用导致视图拖动 & 苹果识别二维码的位置上移

### ISSUE THREAD

**Issue by didiself** [amfe/lib-flexible#102]
有2个问题，都是在wechat里面出现的：

1、活动页使用了rem，点击链接跳转到px项目里，然后点击左上角的返回，回到rem页面，此时的视图可以左右拖动（刚进来的时候不会，页面也没有超出的问题）；

rem => px => rem 
=> 页面拖动

2、在rem的页面中，img里含二维码的，安卓长按可识别，苹果的识别位置会上（还是下？忘了）移；
（如果非要用rem的话，将img设成bg，实际img透明，img位置上移+padding也可以实现）

以上的两个问题，如果设置viewport的话，非动态生成都可以解决；

**Comment by airen** [comment]
此问题和 #99 合并在一起
