### ISSUE TITLE
Android高清屏字体放大

### ISSUE THREAD

**Issue by nimiumiu** [amfe/lib-flexible#103]
Android现在也有很多是高清屏，dpr=1，字体手机上显示是放大的

**Comment by airen** [comment]
后续版本已修改dpr = 1的这个限制

**Comment by nimiumiu** [comment]
判断dpr，在if (isIPhone) 中才有区分，其余系统机型都为1，你修改if (isIPhone)中的判断是无效的

**Comment by nimiumiu** [comment]
Android下获取的win.devicePixelRatio不一定准确，所以作则才赋值为1吧

**Comment by nimiumiu** [comment]
Android下获取的win.devicePixelRatio不一定准确，所以作者才赋值为1吧

**Comment by Phieo** [comment]
这个问题还是没修复吗？安卓还是默认dpr还是1字会很大的。。

**Comment by lian-xiao-xi** [comment]
是啊，安卓默认dpr=1这个问题 还是没有修复 @airen @Phieo
