### ISSUE TITLE
圆角bug.

### ISSUE THREAD

**Issue by chrisbobi** [amfe/lib-flexible#104]
设置圆为宽高0.28rem，border-radius:100%,多写几个圆，有些显示的为椭圆，根本就不是正圆。

**Comment by terrykingcha** [comment]
border-radius直接写0.14rem试试

**Comment by fhqdgv** [comment]
遇到同样的问题

**Comment by zuibunan** [comment]
对于这种场景，建议通过data-drp给元素设置不同的宽高，要确保宽高是整数，否则就可能会出现不圆的情况

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
