### ISSUE TITLE
华为畅享5S手机的微信浏览器出现显示不全的问题.

### ISSUE THREAD

**Issue by NMTuan** [amfe/lib-flexible#105]
今天在测试页面发现这台手机显示的页面超出了屏幕宽度, 出现水平滚动条...
如下图(模拟效果)
![image](https://cloud.githubusercontent.com/assets/2149763/20994026/e363c958-bd28-11e6-8528-d23db5a5aa55.png)
正常效果
![image](https://cloud.githubusercontent.com/assets/2149763/20994043/f87422c0-bd28-11e6-8bf7-a54b205efe8e.png)

经调试发下
```js
'winWidth:' + $(window).width() + '|\n' +
            'docWidth:' + $(document).width() + '|\n' +
            'screenWidth:' + screen.width + '|\n' +
            'getBoundingClientRect:' + document.documentElement.getBoundingClientRect().width + '|\n' +
            'devicePixelRatio:' + window.devicePixelRatio + '|\n' +
            'dpr:' + window.dpr + '|\n' +
            'rem:' + window.rem + '|\n' +
            'appVersion:' + window.navigator.appVersion
```
![image](https://cloud.githubusercontent.com/assets/2149763/20993814/b5c36b58-bd27-11e6-9e4d-c3b3bae3c8b9.png)

尝试强制html或body宽度, 依旧无法解决问题..
不知各位有无解决思路. 谢谢!

**Comment by NMTuan** [comment]
补充一下 系统为安卓5.1 eui 3.1

**Comment by terrykingcha** [comment]
flexible.js，请确保内联在html中，并放在所有js和css之前（head中）

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html

**Comment by yowhat** [comment]
楼主这个问题解决了吗？
