### ISSUE TITLE
如果再用比如日期插件，但是这个插件使用px写的，那在ios下会出现偏小的问题，这个怎么解决

### ISSUE THREAD

**Issue by sjn221314** [amfe/lib-flexible#107]
如果再用比如日期插件，但是这个插件使用px写的，那在ios下会出现偏小的问题，这个怎么解决

**Comment by bluemind7788** [comment]
这个自适应的方案通过vieport的scale进行了缩放，devicePixelRatio大于的1的都会进行相应的缩放。要解决那个问题只能用这个库的方案改写第三方插件的css

**Comment by terrykingcha** [comment]
你可以强制让scale保持1，scale缩放只是为了显示1px的线。
