### ISSUE TITLE
屏幕的宽度是否可以取sreen.width

### ISSUE THREAD

**Issue by git-lt** [amfe/lib-flexible#108]
我在实现这个的时候，如果取document.body.clientWidth是放大后的宽度，如在375宽度的屏幕，dpr=2,下取到的是750px，如果要取到真正的屏幕宽度是否可以直接取 sreen.width?

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
