### ISSUE TITLE
什么时候和tbcdn上lib-flexible版本号同步？

### ISSUE THREAD

**Issue by itbeihe** [amfe/lib-flexible#109]
tbcdn上的lib-flexible已经更新0.3.4了，此项目还是0.3.2，什么时候同步下？对比0.3.2，0.3.4修复了init meta无效的问题，这个bug修复挺需要同步的。
现在有6个pull request未处理了，github上的lib-flexible还有人在维护不？

**Comment by HADB** [comment]
+1，我们团队使用lib-flexible发现iPad的适配有问题，打算做一些改进，但是此repo中的版本和tbcdn上版本又不一致，此项目是否还更新？不更新的话，是否可以转让项目，让社区进一步维护？

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
