### ISSUE TITLE
系统字体变大页面错乱

### ISSUE THREAD

**Issue by xiaomaisu** [amfe/lib-flexible#110]
看到淘宝首页采用的方案是这种，所以想问下因为rem基准为px的话，可能会存在[mp.weixin.qq.com/s?__biz=MzAxODE2MjM1MA==&mid=2651551510&idx=1&sn=ad6f87385c39c90c2501ca94b5f5c8dc&chksm=8025a0d7b75229c1c4fa159c06b7622206fab5d23ab009374608d5935f5a598b776ba8848497&mpshare=1&scene=1&srcid=1204JJsOV7tUq33bezFyWguE#rd]中提到的受系统字体大小影响而页面错乱的问题，不知道怎么处理，可以更换成rem为百分比的方案么

**Comment by yibingxiong** [comment]
字体还是用px为单位，用媒体查询方法适配不同dpr 和屏幕尺寸。没有去研究百分比作为字体大小单位。
希望能帮到您，如有其他看法可来信交流，共同进步
发自网易邮箱大师
在2017年01月10日 19:05，xiaomaisu 写道:

看到淘宝首页采用的方案是这种，所以想问下因为rem基准为px的话，可能会存在[mp.weixin.qq.com/s?__biz=MzAxODE2MjM1MA==&mid=2651551510&idx=1&sn=ad6f87385c39c90c2501ca94b5f5c8dc&chksm=8025a0d7b75229c1c4fa159c06b7622206fab5d23ab009374608d5935f5a598b776ba8848497&mpshare=1&scene=1&srcid=1204JJsOV7tUq33bezFyWguE#rd]中提到的受系统字体大小影响而页面错乱的问题，不知道怎么处理，可以更换成rem为百分比的方案么

**Comment by budapeisidajiudian** [comment]
遇到了类似问题同问

**Comment by crowphy** [comment]
这个问题直接原因是由元素没有指定高度引起的，根本原因是因为触发了webkit内核浏览器的Font Boosting特性，通过设置该元素的高度或者给body指定个max-height可以避免触发该特性。

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html

**Comment by daolou** [comment]
加上这个:
```
        window.onload = function () {
            setTimeout(function () {
                ;(function(){
                    try{
                        var html = document.querySelector('html');
                        var docEle = document.documentElement;
                        var realFz = parseInt(window.getComputedStyle(html).fontSize.replace('px',''),10); // 1rem的实际展示px值
                        var expectFz = parseInt(docEle.clientWidth / 10,10); // 1rem的理论值
                        console.log(realFz,expectFz)
                        if(realFz != expectFz&&docEle.clientWidth<750){//不相等 则被缩放了
                            var realRem = expectFz/(realFz/expectFz); //将期望值除以放大倍率
                            console.log(realRem);
                            html.style.fontSize = realRem + 'px';
                        }
                    }catch(e){
                        console.error(e)
                    }
                })();
            }, 10);
        }
```
