### ISSUE TITLE
用flexible布局不能跟原生保持一致

### ISSUE THREAD

**Issue by xingangsun** [amfe/lib-flexible#112]
我比对了一下，用px单位布局才能和原生写出的页面页面保持一致。用flexbile这种布局还是不太对

**Comment by crowphy** [comment]
这个应该要看设计稿的规格，flexible的像素单位是物理像素（比如iPhone6的750像素），通常是以css像素为单位的两倍或者三倍
个人理解

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
