### ISSUE TITLE
关于低分辨率 安卓手机

### ISSUE THREAD

**Issue by w550** [amfe/lib-flexible#113]
if (!dpr && !scale) {
        var isAndroid = win.navigator.appVersion.match(/android/gi);
        var isIPhone = win.navigator.appVersion.match(/iphone/gi);
        var devicePixelRatio = win.devicePixelRatio;
        if (isIPhone) {
            // iOS下，对于2和3的屏，用2倍的方案，其余的用1倍方案
            if (devicePixelRatio >= 3 && (!dpr || dpr >= 3)) {                
                dpr = 3;
            } else if (devicePixelRatio >= 2 && (!dpr || dpr >= 2)){
                dpr = 2;
            } else {
                dpr = 1;
            }
        } else {
            // 其他设备下，仍旧使用1倍的方案
            dpr = 1;
        }
        scale = 1 / dpr;
    }

这里   if (isIPhone)  为什么只判断iphone呢？
改为  if (isIPhone || isAndroid)  显示效果挺好啊。
你们这样设置的目的是什么，求解

**Comment by SuPeRZ66** [comment]
安卓设备的dpr比较多而且有的不是整数，这样有时候字体效果不好，你可以只判断dpr为整数的安卓设备。

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
