### ISSUE TITLE
使用flexible之后，页面加载的时候，总是页面的文字和格式全部放大然后加载完成再变成正常

### ISSUE THREAD

**Issue by mangoqili** [amfe/lib-flexible#114]
使用flexible之后，页面加载的时候，总是页面的文字和按钮样式全部放大然后加载完成再变成正常。如果页面有弹窗也是会这样。
我的使用方法是在头部最先引入flexible.js：
<head>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta content="telephone=no" name="format-detection"/>
  <meta content="email=no" name="format-detection"/>
  <script type="text/javascript" src="./js/flexible.js"></script>
  <title>干洗服务</title>
  <link rel="stylesheet" href="./css/swiper-3.4.0.min.css">
  <link rel="stylesheet" href="./css/base.css">
  <link rel="stylesheet" href="./css/index.css">
  <link rel="stylesheet" href="./css/iconfont_css/iconfont.css">
</head>

**Comment by zackfly** [comment]
因为 他实习的原理是rem。当js加载完之前，html上的font-size会先影响到使用rem的元素。
检查下用flexible之前 ，html上的font-size。

**Comment by mangoqili** [comment]
css的body和html都不曾设置font-size

**Comment by mangoqili** [comment]
css的body和html都不曾设置font-size

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
