### ISSUE TITLE
IPhone6手机body的font-size被设置为75px了，导致页面元素都变大了

### ISSUE THREAD

**Issue by erguotou520** [amfe/lib-flexible#115]
dpr为2，body的font-size不应该是37.5么？是我理解的有问题？

**Comment by li305263** [comment]
还有scale。 dpr2 ,scale应该是0.5吧

**Comment by erguotou520** [comment]
没注意，后来发现是因为`lib-flexible`放到了`viewport`前面了，放到后面就好了，但是dpr变成了1

**Comment by crowphy** [comment]
建议结合px2rem插件

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
