### ISSUE TITLE
OPPO R9在QQ上打开出现页面不全的情况

### ISSUE THREAD

**Issue by Chu-si** [amfe/lib-flexible#116]
跟下个面的华为是一样的  只是由于客户手机是这个型号 所以无法具体测试问题 不过能够确认的是 同样的方式打开淘宝也是同样的问题   且用自带及下载的浏览器不会出现这个问题

**Comment by iceshu** [comment]
源码是判断大于540就 不缩放啥的了 你改下源码里的这个

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
