### ISSUE TITLE
flexible源码有些不明白，求大神支招，thanks

### ISSUE THREAD

**Issue by Kico-Yu** [amfe/lib-flexible#117]
有一些属性的设置感觉根本没有用到，不清楚作用是什么
![_031617_011142_pm](https://cloud.githubusercontent.com/assets/18063262/23982855/337f236e-0a4b-11e7-855d-c298a2ae62e1.jpg)

**Comment by jeneser** [comment]
Hi，thx for your issue.
Please read the [doc](https://github.com/amfe/lib-flexible/blob/master/README.md) and [demo](https://github.com/amfe/article/issues/17) carefully.You can visit the [article](https://github.com/amfe/article),Google and QQ groups for more information.
please learn how to use GitHub.We need github.We need to protect github.
Thanks.

**Comment by ProceedCheng** [comment]
@jeneser please reply in chinese for those who chinese commiters

**Comment by longshihui** [comment]
这个应该是浏览器端用的API，有些插件不支持rem计算，通过api可以对单位进行相互转换
