### ISSUE TITLE
用flexible以后还需要切不同尺寸的图吗

### ISSUE THREAD

**Issue by longshihui** [amfe/lib-flexible#118]
移动端图片尺寸有@1x @2x @3x，使用rem单位进行布局 还需要切不同尺寸的图？图片的尺寸需要使用rem吗？默认使用@3x的图?

**Comment by zxpsa** [comment]
不需要吧。。我们基本上是用750的图就可以了。。。在各种屏上组件尺寸都比较接近

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
