### ISSUE TITLE
refreshRem函数中为什么width/dpr > 540 的都设置为540*dpr

### ISSUE THREAD

**Issue by lidianhao123** [amfe/lib-flexible#12]
以下代码：
 var width = docEl.getBoundingClientRect().width;
        if (width / dpr > 540) {
            width = 540 * dpr;
        }
如此设计的原理是什么呢？

**Comment by jincdream** [comment]
这里预先定义了，大于540宽度(除以像素比之后就是设备宽度了)的基本就不是mobile设备了，可能是平板或者电脑了。540也是比较合理的一个数值。

**Comment by terrykingcha** [comment]
这个540其实是个经验值，或者最大值，这个经验是怎么得出来的呢？
目前主流手机最大的css像素尺寸，是540（比如devicePixelRatio为2，分辨率是1080x1920的手机），所以用了这个经验值。这样可以让在ipad横屏这种情况下浏览无线页面，不至于因为拉伸适配后体验太差。

**Comment by codekissyoung** [comment]
@terrykingcha 可这样子的话，10rem就不是iPad浏览器的宽度了呀！！！

**Comment by codekissyoung** [comment]
@terrykingcha 刚看了下手机淘宝，两边留空白感觉丑啊，用户体验更不好吧！

**Comment by dd1994** [comment]
iPad 还是建议不要跟手机搞一套适配，太大了。。。

**Comment by jiangyanghe** [comment]
540 有啥数据依据吗？

**Comment by mingelz** [comment]
@jiangyanghe 在前边 @terrykingcha 已经解释了 540 是怎么来的：1080 / 2(dpr)
