### ISSUE TITLE
flexible 1px 问题

### ISSUE THREAD

**Issue by SlimJason** [amfe/lib-flexible#120]
1px 的border。。。。我发现有时候，有的浏览器出现不了

**Comment by longshihui** [comment]
考虑使用/*px*/ ？

**Comment by lyre2468** [comment]
+1    如果用boder-bottom: 1px solid #f5f5f5; 某些手机渲染不出来。boder-bottom: 1px solid #f5f5f5； /*!no*/ 能渲染出来。

**Comment by longshihui** [comment]
我最近也遇到了 flexible对android设备设置的dpr 都是1  在750的dpr2的设计稿下 出现小数 一些浏览器直接解析成0了

**Comment by lyseky** [comment]
360n4s 自带浏览器边框不出来，坑啊

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
