### ISSUE TITLE
字体不用rem作为单位，字体超出容器大小？

### ISSUE THREAD

**Issue by ygtzz** [amfe/lib-flexible#123]
iphone6，iphone5，iphone4的dpr都是2，但是其屏幕尺寸确不同，若容器安装750设计稿的rem布局，字体在iphone5时会超过容器大小，请问这个问题是如何解决的？

**Comment by tiamoyajie** [comment]
rem+media query

**Comment by zxpsa** [comment]
根据dpr设置对应的px 就好了。。。我们一般是工具 自行达成

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
