### ISSUE TITLE
能出个webpack打包方案吗

### ISSUE THREAD

**Issue by leeseean** [amfe/lib-flexible#124]
grunt现在都没人用了

**Comment by channg** [comment]
npm install lib-flexible
import 'lib-flexible'

**Comment by iceshu** [comment]
。。。webpack 用postcss 这样写的时候还是px方法写  他会自动把你转成rem

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
