### ISSUE TITLE
用vue 开发能应用 flexible，主要问题是 css 写在 .vue 文件中 

### ISSUE THREAD

**Issue by shahuyang** [amfe/lib-flexible#125]

**Comment by shahuyang** [comment]
nothing

**Comment by iceshu** [comment]
简单的啊 你用postcss 写的时候还是按照px的方法去写然后用pxtorem 自己做转换就好

**Comment by lovebeyond** [comment]
谢谢！
----- 原始邮件 -----
发件人：iceshu <notifications@github.com>
收件人：amfe/lib-flexible <lib-flexible@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[amfe/lib-flexible]_用vue_开发能应用_flexible，主要问题是_css_写在_.vue_文件中_(#125)
日期：2017年05月05日 15点50分

简单的啊 你用postcss 写的时候还是按照px的方法去写然后用pxtorem 自己做转换就好

&mdash;

**Comment by twoer** [comment]
LZ 可以参考我的 Demo https://github.com/ZHF-Road/vue-cli-webpack-scss-px2rem-demo

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
