### ISSUE TITLE
使用flexible自动设置的meta标签时，页面H标签内的文字无法居中

### ISSUE THREAD

**Issue by fantasy525** [amfe/lib-flexible#132]
当时用flexible.js自己设置的meta时在h2标签设置text-align后文字居中失效，无法居中了，后来我发现在meta上加上width=device-width后就可以了，我现在想知道有没有其他解决办法？这个可能是个bug,之前看文章说width=device-width和initial-scale=1的作用是差不多，为什么淘宝开发代码时没有加上呢，是加上后有其他bug吗？

**Comment by benzhemin** [comment]
同问

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
