### ISSUE TITLE
富文本输出的字体太小

### ISSUE THREAD

**Issue by NicholasNC** [amfe/lib-flexible#137]
因为在2倍屏下，将 viewport 的 scale 设成0.5，这样富文本出来的文章内容里面如果设置了字体大小，例如：10px、18px 的话，在 iOS 下字体就特别小。

我现在的做法是拿到富文本输出的字符串之后，用 js 将 `<p style="font-size: 18px;">我是富文本输出的内容</p>` 匹配 `font-size: 18px;` 然后乘以 `data-dpr` 。

觉得这样有点麻烦。

不知各位是如何解决这个问题的。

**Comment by w455246851** [comment]
我也遇到了这种问题，目前也没有找到解决的方法，你这种之前也想过，但是不是很实用，flexible也不更新了，现在也很郁闷啊

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
