### ISSUE TITLE
页面中存在iframe的话在dpr大于1的时候怎么适配呢，整个iframe被缩成1/dpr了。。。。

### ISSUE THREAD

**Issue by fisherw** [amfe/lib-flexible#138]
目前想到的是用scale放大dpr倍，然后将它的容器高宽恢复成dpr倍。求更好的解决方案。

**Comment by MichaelIT** [comment]
+1

**Comment by lovebeyond** [comment]
ok
----- 原始邮件 -----
发件人：Michael <notifications@github.com>
收件人：amfe/lib-flexible <lib-flexible@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[amfe/lib-flexible]_页面中存在iframe的话在dpr大于1的时候怎么适配呢，整个iframe被缩成1/dpr了。。。。_(#138)
日期：2017年06月10日 16点46分

+1

&mdash;

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
