### ISSUE TITLE
今天看了源码 有点不明白

### ISSUE THREAD

**Issue by riskers** [amfe/lib-flexible#14]
1. 在`refreshRem`中:
	```
	        if (width / dpr > 540) {
	            width = 540 * dpr;
	        }
	```
	意义是什么？540是哪里来的？
	看到 #12 也是这样的问题。

2. 最后为什么要给body设置`font-size`？我去掉了，似乎也没有什么影响。

	之前没用过，只是看源码的时候有点不明白。希望赐教。

**Comment by JackZhang1988** [comment]
我也有同样的问题，有没有人解答一下？

**Comment by terrykingcha** [comment]
这个540其实，其实是个经验值，或者最大值，这个经验是怎么得出来的呢？
目前主流手机最大的css像素尺寸，是540（比如devicePixelRatio为2，分辨率是1080x1920的手机），所以用了这个经验值。这样可以让在ipad横屏这种情况下浏览无线页面，不至于因为拉伸适配后体验太差。

**Comment by prp632791853** [comment]
我也是你看了半天，540是什么鬼？

**Comment by dianniu** [comment]
这个库很好，但是感觉不怎么更新有点吓人……

**Comment by lgh06** [comment]
@dianniu 一共也没几行 自己改一改好了……感觉放在这里的是个半成品……

**Comment by airen** [comment]
@dianniu @lgh06 这个库并不是什么半成品。手淘很多业务中都在使用这个库。https://github.com/amfe/article/issues/17

**Comment by dd1994** [comment]
magic number...
