### ISSUE TITLE
你好，请问为什么不更新了（已经看到别人用 0.3.4版本的了）？

### ISSUE THREAD

**Issue by GreatAuk** [amfe/lib-flexible#140]
我已经看到有人用 0.3.4 版本的了，为什么 github 上不更新了呢？
http://g.tbcdn.cn/mtb/lib-flexible/0.3.4/??flexible_css.js,flexible.js

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
