### ISSUE TITLE
viewport 缺失width适配

### ISSUE THREAD

**Issue by benzhemin** [amfe/lib-flexible#142]
我的理解，对viewport的width的适配，以iphone6为例，先假设屏幕宽是width(375)*dpr(2), 然后设置scale=1/2，得到css的布局实际还是375，以上说法是否正确？
但是整个flexible.js没有看到width=clientWidth * dpr这样的代码，默认好像就没有设置。然后我查阅文档，如果没有设置width，默认采用layoutviewport，宽度是980，实际的宽度是怎样设置的？

**Comment by bestao** [comment]
在没有设置scale = 1/2 之前， 1个css像素对应了2个物理像素。 设置了scale之后， 1个css像素对应了1个物理像素。如果不设置width，由于scale是0.5，所以width为750px

**Comment by airen** [comment]
新提供的适配方案：https://www.w3cplus.com/css/vw-for-layout.html
