### ISSUE TITLE
为何非苹果设备不需要设置scale，比如安卓机

### ISSUE THREAD

**Issue by bestao** [amfe/lib-flexible#143]
![dpr](https://user-images.githubusercontent.com/9649804/28359067-a4fd6e64-6ca3-11e7-8723-912fd4dfcd41.png)
有什么特别的考虑吗？

**Comment by airen** [comment]
@bestao 可以开始尝试这篇文章提到的适配方案：https://www.w3cplus.com/css/vw-for-layout.html
