### ISSUE TITLE
为什么限制rem最大对应54px？

### ISSUE THREAD

**Issue by imseon** [amfe/lib-flexible#145]
`var width = docEl.getBoundingClientRect().width;
  if (width / dpr > 540) {
    width = 540 * dpr;
  }`
也就是上面这段代码是什么作用？

**Comment by airen** [comment]
当初设计的时候采用的一个蛋疼的hack手段。建议开始弃用,改用vw吧：https://www.w3cplus.com/css/vw-for-layout.html

**Comment by edeink** [comment]
我刚接手的一个项目，其中就引用了lib-flexible，我也非常困惑54px的上限设置，因为是上线的项目，在未全部改用为vw之前，请问大漠老师，这段hack是为了解决一个什么样的问题的？假若我去掉if判断，会造成什么通用影响？[#12](https://github.com/amfe/lib-flexible/issues/12)
