### ISSUE TITLE
html标签中没有data-dpr属性了，css中怎样查询dpr啊

### ISSUE THREAD

**Issue by lf7817** [amfe/lib-flexible#147]
html标签中没有data-dpr了，css中怎样查询dpr啊，怎样适配字体

**Comment by mingelz** [comment]
@lf7817 可以继续使用之前的 0.3.2 版本。目前的新版本，以 device-width 为基础，不需要根据 dpr 分两个字体大小了。

**Comment by lf7817** [comment]
好的，谢谢了，还是用新版吧

**Comment by njleonzhang** [comment]
@mingelz 新版本的字体怎么写呢？ 直接写rem么
