### ISSUE TITLE
这个库跟阿里CDN怎么不一样

### ISSUE THREAD

**Issue by Max-Law** [amfe/lib-flexible#148]
<script src="http://g.tbcdn.cn/mtb/lib-flexible/{{version}}/??flexible_css.js,flexible.js"></script>

阿里CDN有两个文件，这个库的index只有一点代码，倒是那个才是flexible的解决方案

**Comment by HeYaxun** [comment]
在 readme 里面点击 Classic edition (0.3.2)

**Comment by Max-Law** [comment]
谢谢，我进去后看了推荐的 《再聊移动端页面的适配》，大漠老师是用 vw，vh，来解决适配问题，比现flexible的hack技术要优雅点。但是看了看，还是存在机型的不兼容，我现在的项目要面向的范围较大，还是原生 H5 混合开发，app里用的应该是原生浏览器的内核，这就让我很纠结。flexible的hack方式看文章似乎在 iframe 的使用上存在问题，所以先问下您在使用这么久的flexble，会存在什么比较麻烦的问题吗？

**Comment by mingelz** [comment]
@Max-Law 这次的 2.0 版本，支持 iframe，支持 canvas，不存在问题。且有 [postcss-adaptive](https://www.npmjs.com/package/postcss-adaptive) 作为开发辅助，与之前的版本开发体验一致。

**Comment by Max-Law** [comment]
@mingelz 源码中是安卓设备dpr为1，苹果只分1，2，然而现在安卓设备也有许多retina，iphone6 + 也是dpr为3了。所以我自己想了一个方案，<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">  //固定布局视口等于device-width，一比一不再动态改变，只根据设备宽度动态设置html的fontsize，在利用rem布局，在retina图片则用，sass编辑一个混合宏，用媒体查询实现。你看看这个方案是否可行，谢谢~

**Comment by airen** [comment]
@Max-Law 这个太绕了，换换vw吧。https://www.w3cplus.com/css/vw-for-layout.html

**Comment by Max-Law** [comment]
@airen 应该在安卓4.3以上才能使用，而且很多国产机改过内核，真的不确定兼容性，小米，华为这种疯狂改的就是很好的例子

**Comment by mingelz** [comment]
@Max-Law 是的，现在 2.0 的版本就是固定 device-width，然后根据设备宽计算出 rem 备用，绝大多数场景使用 px 台机器。

**Comment by whatwg6** [comment]
m
