### ISSUE TITLE
VW适配的方案能否也跟Flexible一样出一个Sublime Text的换算插件

### ISSUE THREAD

**Issue by yowhat** [amfe/lib-flexible#149]
VW适配的方案能否也跟Flexible一样出一个Sublime Text的换算插件 。

**Comment by zhiqiang21** [comment]
用预编译css语言的话写一个换算的函数就可以了。然后再定一个编辑器的代码段，自动补全函数。

**Comment by mingelz** [comment]
其实更建议使用 postcss 之类的预/后处理工具完成转换工作。这样能够保证源码的可读性。编辑器插件直接在源码编辑阶段就生成了目标数字，后续维护并不方便。对于 0.3.2 版本，有 [px2rem](https://www.npmjs.com/package/px2rem)，对于目前的 2.0 版本，有 [postcss-adaptive](https://www.npmjs.com/package/postcss-adaptive)

**Comment by njleonzhang** [comment]
@mingelz 2.0版本的用法似乎不太一样了，有没有文档呢
