### ISSUE TITLE
完整引用举例里写的是什么看不懂

### ISSUE THREAD

**Issue by wa15aa** [amfe/lib-flexible#15]
如题

**Comment by handoing** [comment]
把<script src="http://g.tbcdn.cn/mtb/lib-flexible/{{version}}/??flexible_css.js,flexible.js"></script>中的{{version}}替换为选择的js版本
例如当前版本为0.3.2那么引入<script src="http://g.tbcdn.cn/mtb/lib-flexible/0.3.2/??flexible_css.js,flexible.js"></script>
这种方法是通过cdn直接引入，是./build/flexible_css.debug.js和./build/flexible.debug.js压缩之后的。

**Comment by airen** [comment]
更详细的示例可以参考这个：[https://github.com/amfe/article/issues/17](https://github.com/amfe/article/issues/17)
