### ISSUE TITLE
2.0方案是不是就用rem单位去写字体大小？

### ISSUE THREAD

**Issue by njleonzhang** [amfe/lib-flexible#151]
请问2.0方案是不是直接用rem去写字体大小？

**Comment by airen** [comment]
尝试一下不就知道了？但还是尽量尝试去使用`vw`来做移动端的布局吧

**Comment by njleonzhang** [comment]
用rem或者vw去写没有小数字体的问题么？直接忽视了么。这是best pratice?

**Comment by mingelz** [comment]
使用 postcss-adaptive 插件，rem 会自动转换。因为 2.0 方案默认以 device-width 为宽度，所以大部分情况下不需要用 rem 做单位。
