### ISSUE TITLE
获取屏幕宽度方式改进

### ISSUE THREAD

**Issue by trancelover** [amfe/lib-flexible#153]
document.documentElement.getBoundingClientRect().width
获得的宽度和设备屏幕宽度并不是始终相等。
客户端中webview 做预加载，这个宽度取得的是view的宽度，
而非设备屏幕宽度（取决于view不可见时的默认显示宽度），
造成第一次点击view 的渲染跳动。
实为font-size的重新计算。
改进为 screen.width*window.devicePixelRatio  可获得设备的实际宽度。
当然 安卓下还是 devicePixelRatio 默认取1.

**Comment by mingelz** [comment]
在 2.0 中直接取的 document.documentElement.clientWidth
