### ISSUE TITLE
flexible2.0对比0.3.2改进的地方没有看懂

### ISSUE THREAD

**Issue by ZhaZhengRefn** [amfe/lib-flexible#154]
2.0似乎只是dpr为1的0.3.2的版本，没看懂什么意思，完全放弃对retina设备的支持？

**Comment by mayorhao** [comment]
我也有这个疑问。还请解答

**Comment by xiaolongyuan** [comment]
+1

**Comment by jxp4531** [comment]
2.0抛弃了rem方案，使用了vw，详见 https://www.w3cplus.com/css/vw-for-layout.html

**Comment by airen** [comment]
Flexible并没有2.0一说，也和`vw`没有任何关系：[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)
