### ISSUE TITLE
请问项目中如果按大漠的博客一样配置了 还需要引入这个库么？

### ISSUE THREAD

**Issue by xiaolongyuan** [amfe/lib-flexible#159]
https://huodong.m.taobao.com/act/layouttestvw.html
因为博客中举得这个示例 发现根本没有用这个库的代码

**Comment by xiaolongyuan** [comment]
@airen

**Comment by maczyt** [comment]
不用了

**Comment by airen** [comment]
@xiaolongyuan 请自己看清楚了再说，示例没有引用这个库的代码？

**Comment by xiaolongyuan** [comment]
@airen 我是右键查看源代码 搜索了 pageshow 和 resize  fontSize  关键字  发现并不存在这些关键字
 还有个就是 
![image](https://user-images.githubusercontent.com/3142363/32088962-ba3df522-bb19-11e7-808d-9d706d80d321.png)
并没有设置字体大小  所以才有疑问

**Comment by airen** [comment]
如果你使用的是`vw`布局，那么和flexible并没有任何关系了。如果你对`vw`的兼容还存在一定的困绕，那这篇文章可以给你提供一定的参考意见：[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)

**Comment by xiaolongyuan** [comment]
@airen thanks
