### ISSUE TITLE
flexible2.0与flexible0.3.4到底应该如何抉择？好纠结！

### ISSUE THREAD

**Issue by lian-xiao-xi** [amfe/lib-flexible#160]
flexible2.0是放弃了高清屏吗？

**Comment by xiaozhukl** [comment]
现在最新版是0.4.1

**Comment by dbl520** [comment]
哪个版本合适？能写个教程么？

**Comment by airen** [comment]
为什么会有flexible 2.0一说呢？前段时间发布的`vw`布局和flexible并没有半点关系。首先要搞清楚他们的区别。如果你需要教程，可以参阅：[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)
