### ISSUE TITLE
在努比亚自带浏览器中(dpr为3，360*519)，此方法不再适用

### ISSUE THREAD

**Issue by duenyang** [amfe/lib-flexible#161]
发现页面两边会有空白部分，经测试发现给页面根节点赋值的字体大小为48px,但是浏览器使用的是32px左右的字体，不知是什么原因...，页面中也没有重新赋值的操作，并且在其它浏览器中都是正常的...

**Comment by HopeLyn** [comment]
小米+1，dpr 3，宽 360。赋值 36px，浏览器使用 30.96 字体

**Comment by xihadandan** [comment]
你们用的是什么flexible2.0还是flexible0.3.4，flexible0.3.4不是设置安卓dpr为1吗

**Comment by HopeLyn** [comment]
用的 2.0

**Comment by xihadandan** [comment]
2.0不是vw vh吗？vw vh也是会有问题吗？目前在用0.3.4，因为vw还有些浏览器不支持

**Comment by airen** [comment]
Flexible并没有2.0之说。而且整个Flexbile的设计思想是参考`viewport`的原理的，但其并不是`vw`、`vh`来布局的。这一点需要先整请楚。另外Flexbile也并不是说直接用`rem`就可以实现适配，它也是需要依赖于`flexible.js`来修改`html`的`font-size`，再借助`rem`来做相关的事情。真的`vw`布局是这样的：[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)
