### ISSUE TITLE
2.0 body-size 的疑问

### ISSUE THREAD

**Issue by f2009** [amfe/lib-flexible#163]
请教,为什么要加body-size属性?
这是出于一种什么样的考虑呢,加上后会起到一个什么样的作用?
谢谢!

**Comment by icebloodzs** [comment]
全部使用rem的确用不到，我觉得加上可能为使用em方便吧

**Comment by Syntaxe3** [comment]
我手动把2.0中这一段代码移除了😕😒

**Comment by TongDaDa** [comment]
使用rem为字体设置大小会出现浮点数，在某些设备下会出现模糊和`舍入`像素的情况。

具楼上所说，body-size 这个功能是为了em，起初我也是这么想的，并尝试实验了一下。

结果：

1. 移动端使用 em 来设置字体会造成不能实时同步。使用em大多数就是两种情况，css queries 还有刚才说的这种方式，暂且叫做根据设备信息设置 `基础字号` 吧。但是它们都有弊端的时间，不能像 flexible rem那样实时性更新，肯定会造成在一些设备上的不适配. 而使用rem呢？上面的弊端也说了，会因为浮点造成模糊和舍入像素导致的问题。 对于这个我也比较困惑，先请教大家一下。

2.  根据 dpr 来倍增 12px并没有什么意义，在viewport 其 device-width 已经按 drp 缩小了页面的视区，假设 1080p手机 => 360(dpr = 3) 。所以在 360 的视口区域下，根据dpr来放大fontSize 没有任何作用，反而加上会造成页面的一些问题。不懂意义何在？ 


期待牛人的完美回答！为我解惑，感激不尽。

**Comment by freetwh** [comment]
动态设置body的font-size导致很多间隙动态的变化！！！浪费了我一天时间调样式。决定手动删除

**Comment by Mr-shao** [comment]
我也是看到这块代码有疑问在Issues找答案的，加了setBodyFontSize明明就是没有意义的啊，只会让字体在不同dpr设备初始字体差距更大，鸡肋么？还是另有用途。。。

dpr不就是解决设备字体大小的问题的么

**Comment by airen** [comment]
起初是为了初始化`font-size`。Flexbile在不知情的情形下会触发`font`怪异的渲染现象，的确是一件蛋疼的事情。很多时候没有真实的case，也很难定位。不过现在基本不对Flexbile做相关更新维护。目前开始使用`vw`来做移动端适配布局。《[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)》一文提供了兼容低于Android 4.4 和iOS8.0 的设备。后续会整理一篇有关于Flexbile项目无缝过渡到`vw`布局的方案。
