### ISSUE TITLE
为何不直接把dpr设置成1呢，求大大稍微点拨一下

### ISSUE THREAD

**Issue by BlackEyeByLee** [amfe/lib-flexible#166]
因为项目中与vux冲突了，适配方案是用的把vux组件转成PX，然后自己的代码用rem2px转一下，但是因为dpr缩放的关系，导致vux本身组件的内容被缩放了。目前自己的解决方案是强行设置dpr为1或者把用到的vux组件样式替换一份。所以就弱弱问句，为何不把dpr设置成1而是根据iphone去设置呢

**Comment by quietTrojan** [comment]
you speak chinese,they will not notice you，please speak englishi.

**Comment by BlackEyeByLee** [comment]
@quietTrojan all right....but i has found the cause for why not set 1 dpr. btw , the chinese is best -- LuXu

**Comment by channg** [comment]
@BlackEyeByLee 为了高分辨率下清晰度原因，减小物理像素与屏幕像素差异。

**Comment by bigbigbo** [comment]
@BlackEyeByLee 最新版本已经全部设置dpr为1了吧...

**Comment by BlackEyeByLee** [comment]
@bigbigbo 你指的的是2.0吗，2.0的没有了解到，不过楼上正解
‘ 为了高分辨率下清晰度原因，减小物理像素与屏幕像素差异。’
