### ISSUE TITLE
跳转到新页面之后 点击返回 计算会出错 iPhone6下应该是37.5px 但是变成了 98px

### ISSUE THREAD

**Issue by Dashumod** [amfe/lib-flexible#168]

**Comment by haozhaohang** [comment]
你没有加meta viewport，加上就可以了。

**Comment by johnqiuwan** [comment]
我的加上meta viewport 反而不能正常缩放，去掉 meta viewport 却一切都正常。本来以为运行的时候会自动添加 meta tag，但是看了 console ，新版本也没有自动添加 meta viewport 的 tag。谁有和我类似的情况吗

**Comment by konanxu** [comment]
@johnqiuwan 和你一样，去掉meta viewport返回还正常了，不知有其他解决方案不

**Comment by airen** [comment]
使用过程并没有复现你所说的这种情形。建议从现在的项目中开始使用`vw`布局：[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)
