### ISSUE TITLE
flexible版本0.3.4，pixel 2 和一加5t设置font-size字体会变大。

### ISSUE THREAD

**Issue by LittleBoy1993** [amfe/lib-flexible#170]
使用flexible时在pixel2和一加5t上会出这个问题，具体是屏幕宽度412，html的font-size也写的是41.2px，但是审查看到实际的font-size是47.38px，设置其他元素的font-size也会变大。
这样布局设置body { width: 10rem; margin: 0 auto; }时就会出现横向滚动条。

**Comment by airen** [comment]
Flexible在一些机型上是会存在这样的问题，建议使用`vw`的布局方案。[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)提供了Vue项目的移动端适配方案。你可以按照类类的方案，在项目中添加所需的PostCSS插件，让你的项目中完美使用`vw`布局

**Comment by LittleBoy1993** [comment]
好的 感谢 后来查清原因是用户将手机默认字体放大会出这个问题 后面用vw试一试看看
