### ISSUE TITLE
vw 为何不配合动态dpr

### ISSUE THREAD

**Issue by wenjayliu** [amfe/lib-flexible#171]
我使用lib-flexible的主要需求就是想是不同dpr 的手机显示图片更见清晰

**Comment by airen** [comment]
图片显示清晰与否和`dpr`是没有关系的，除非你根据不同的dpr提供不同的图片。就算是使用`vw`，你提供的是了`@2x`或者`@3x`的图，那么也是会清晰显示的。另外，你就算是要在不同的地方提供不一样的图片，也不是根据dpr来处理的，而应该考虑 `<picture >`。
