### ISSUE TITLE
vw单位是不是不支持css3transition的过渡？

### ISSUE THREAD

**Issue by vhuangcan** [amfe/lib-flexible#172]
使用新的方案vw；
测试系统：IOS；
transition过渡vw单位生硬。没有过渡效果。。；
测试系统：Android；
transition过渡有效果，大该是因为已经转换成px单位了。

**Comment by airen** [comment]
@vhuangcan 最好能提供示例代码。目前并没有发现你所说的现象

**Comment by vhuangcan** [comment]
@airen 
ios版本:11.2.5
div{
 transition: all 0.3s;
}
div.active{
 transform: translateX(3vw);
}
真机上测试，通过点击加 active 类后，移动生硬。

**Comment by airen** [comment]
@vhuangcan CSS的`transition`是从A状态过渡到B状态。只见A状态，并没有看到B状态。你可以看看在`div`上加上A状态。
