### ISSUE TITLE
flexible 绝对定位

### ISSUE THREAD

**Issue by chnliquan** [amfe/lib-flexible#174]
LZ好，我在用flexible布局的时候遇到了一个绝对定位的坑，页面分为上中下结构
```html
<div class="header"></div>
<div class="body"></div>
<div class="footer"></div>

<style>
.body {
    position: absolute;
    top: 120px;
    botton: 50px
}
</style>
```
上下的距离是通过视觉稿量出来的，但是更换不同的设备，body元素定位没有紧挨着header下面，屏幕小时会盖住header，屏幕大时会和header中间有间距，请问如何解决
ps: 当前这个布局可以用flex解决，但是如果有一个图片，绝对定位在距上xxpx通过动态计算就会有偏差

**Comment by etheranl** [comment]
用postcss的px2rem插件，在需要精确px的样式后面加/*px*/备注

**Comment by chnliquan** [comment]
header的高度（170px）是被里面内容撑高的，这个高度是在视觉稿上将header内所有元素高度加起来算出来的值，如果要精确到px，那么header内的所有元素都需要将高度精确到px才能保证header的高度是170px，然后下面的main容器使用position: absolut, top: 170px; /*px*/才可以。  需要这样实现么？
