### ISSUE TITLE
部分国产机在有软键盘弹出时旋转屏幕字体大小会突然变化

### ISSUE THREAD

**Issue by davinma** [amfe/lib-flexible#178]
部分国产机的软键盘弹出时，如果旋转屏幕再旋转回来，会出现字体突然变化的情况。

建议可以在以下代码：

````` javascript
window.addEventListener('resize', setRemUnit)
`````

后面新增一行：

````` javascript
window.addEventListener('orientationchange', setRemUnit)
`````

即屏幕旋转时重新设置 rem 大小。

**Comment by airen** [comment]
是的，没有添加resize相关的功能，主要是因为手淘不需要考虑横屏的场景。

**Comment by youngjuning** [comment]
@airen 也就是说，他这个是可以考虑使用的对吧。
另外您说那个 vw，目前兼容性应该不好吧

**Comment by airen** [comment]
@youngjuning 我想你是没有仔细看看有关于这方面的文章吧。建议你阅读一下这篇文章：https://www.w3cplus.com/css/taobao-2018-year.html  我想你会改变一些看法的

**Comment by youngjuning** [comment]
@airen 虽然看的头疼，还是坚持看完了，我只想说，我要用 scss 试试
