### ISSUE TITLE
某些情况下IOS pageshow 中获取clientWidth错误导致页面被放大

### ISSUE THREAD

**Issue by belerweb** [amfe/lib-flexible#179]
当前页面用的 flexible 2.2.1 版本，链接跳转到一个使用 1.x flexible版本的页面后再返回上一页的时候，发现页面被放大了。调试后发现 页面打开的时候 和 返回页面的时候 docEl.clientWidth 不一致，从而导致rem不对了。

在浏览器控制执行代码再次检查docEl.clientWidth 又发现正常了。估计是pageshow事件处理函数在某些情况页面viewport还未完成更新。

尝试解决发现可以将 pageshow事件中的 setRemUnit() 改为 setTimeout(setRemUnit)

**Comment by airen** [comment]
其实可以无缝过渡到vw-layout布局了。https://www.w3cplus.com/css/taobao-2018-year.html
