### ISSUE TITLE
请问使用flexible后，其他ui组件会随dpr倍数缩小，请问有什么好的解决方案吗

### ISSUE THREAD

**Issue by luantian** [amfe/lib-flexible#180]

**Comment by longshihui** [comment]
把layout viewport设为idea viewport的大小

**Comment by Wayne529** [comment]
对 我也遇到了这个问题  当初引入weui的时候

**Comment by luantian** [comment]
直接换成amfe-flexible就行了

**Comment by lihuangshuaige** [comment]
换成amfe-flexible 啥意思

**Comment by luantian** [comment]
因为lib-flexible是个过渡版本，有问题，amfe-flexible已经改变了实现方式，不会引起ui缩小了

**Comment by longshihui** [comment]
最主要的原因是2.0里 layout viewport宽度始终等于idea viewport的宽度，老版本主要是通过缩放layout viewport来模拟vw的，当layout viewport缩小的时候 layout viewport 的宽度实际上是大于idea viewport宽度的，而ui库都是固定px来写的，依赖于 layout viewport width = idea viewport width  这是主要原因

**Comment by lihuangshuaige** [comment]
想请问下   这个版本的字体大小用什么单位写   我看没有data-dpr属性了

**Comment by airen** [comment]
可以直接写rem。但建议使用vw布局。
