### ISSUE TITLE
关于vw适配方案的一点疑问

### ISSUE THREAD

**Issue by longshihui** [amfe/lib-flexible#181]
曾经的rem适配方案是通过缩放layout viewport完成css px到物理px的映射关系,
对于新的vw适配方案我有以下两点疑问:
1. postcss-px-to-viewport默认了视觉稿的dpr是2 ？
2. vw适配方案里把layout viewport = idea viewport，那转换出来的vw能否保证css的1px=1物理px？

**Comment by chinawzc** [comment]
有回答吗
