### ISSUE TITLE
这个版本是不是去掉data-dpr属性了？

### ISSUE THREAD

**Issue by lihuangshuaige** [amfe/lib-flexible#183]
这个版本是不是去掉data-dpr属性了？那字体用什么写大小

**Comment by HenryYong** [comment]
我还以为是我的打开方式不对，专门用回了0.3.2

**Comment by ghost** [comment]
data-dpr对应的是设置了meta缩放为0.333333，字体在DPR1/2/3时需要分别写12PX/24PX/36PX
现在meta缩放是1，字体只需要写12px在DPR1/2/3下都是一个效果
如果需要字体根据不同设备改变大小，那就需要使用REM或VW（最新版lib-flexible用的就是VW）

**Comment by whapply** [comment]
@MOONLIGHTV   最新版的 ？ 我看这个两年没更新了啊
