### ISSUE TITLE
关于第一版init-scale的问题

### ISSUE THREAD

**Issue by bless-19946** [amfe/lib-flexible#187]
为什么要通过dpr 来设置init-scale 的大小，这个作用是什么

**Comment by airen** [comment]
@bless-19946 建议改用VW进行布局了。

- [如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)
- [再聊移动端页面的适配](https://www.w3cplus.com/css/vw-for-layout.html)
- [分享手淘过年项目中采用到的前端技术](https://www.w3cplus.com/css/taobao-2018-year.html)
