### ISSUE TITLE
用vw+rem，直接css就能实现这个库效果了

### ISSUE THREAD

**Issue by hzsrc** [amfe/lib-flexible#189]
用一个样式，结合rem单位就实现了响应式伸缩：

// 100vw / 375px = 0.2666667 vw/px
// 为便于换算，设定1rem = 100px, 即 1rem = 26.66667vw。也可根据需要调整数值
html {
    font-size: 26.66667vw !important;
}

性能好且代码简洁。

不知是否有其他考虑？

**Comment by airen** [comment]
请看readme最前面的一段描述
