### ISSUE TITLE
关于flexible_css.debug.js的问题

### ISSUE THREAD

**Issue by handoing** [amfe/lib-flexible#19]
看了下flexible_css.debug.js里动态插入的样式表内容与flexible.debug.css相同，
那么页面引入flexible_css.debug.js与引入flexible.debug.css有什么区别吗？

**Comment by airen** [comment]
两者是一样的，我们只是将flexible.debug.css通过工具转换成js，然后合并在一起，减放请求。你也可以通过`link`方式在`<head>`中引用flexible.debug.css。
