### ISSUE TITLE
关于在wp上的一点问题

### ISSUE THREAD

**Issue by Tankpt** [amfe/lib-flexible#2]
我的一点理解就是将设备的宽度　分割为16等分，那么，我测试了下 document.documentElement．getBoundingClientRect().width在wp手机上获取的是1024，不知道是是不支持这个反人类的浏览器么？还是需要一些特殊的处理

**Comment by ximan** [comment]
lumia 920
screen尺寸，IE为383x638，QQ和UC为480x800
网页宽度都为1024
window.devicePixelRatio像素比，IE为2.0049394673123486，QQ为undefined，UC为1.6
所以这个js不支持Windows Phone是肯定的。

**Comment by huixisheng** [comment]
期待2.0
