### ISSUE TITLE
感觉可以按照切图来先定义好，定义为一个整数比如100，这样rem更好计算

### ISSUE THREAD

**Issue by hhhccckkk** [amfe/lib-flexible#21]
比如我们切图按照750来切的。
那么我们的
font-size计算：

 var c;
            var b = f.getBoundingClientRect().width;
            b / i > 540 && (b = 540 * i);
            var my=750;   //切图按照750计算，就写750,640计算就写640
            if(b==my){     //分辨率=我们切图，直接定死100，或者其他，这里写100，为了好计算rem
              c=100;
            }
            else{
                c=b/my*100;    //其他分辨率的font-size就这样计算
            }

这样做后，我们按照750的切图标注来布局，就方便计算rem了，比如
100px： 100/100=1rem
230px ： 230/100=2.3rem
若按照源代码的话：230px： 230/75=3.066667rem     不好计算

请问这种做法是否会有其他问题？ 谢谢

**Comment by wangjianbing925** [comment]
这样对以后的vw vh单位不好做兼容吧

**Comment by yuu2lee4** [comment]
可以自定义就好了

**Comment by yuu2lee4** [comment]
/*
design_w:初始化（效果图）宽度，
maxW:最大页面宽度，超过这个宽度html fontsize不再变化 建议跟设计图宽度一样
minW:最小页面宽度，小于这个宽度html fontsize不再变化 建议为320
default_fz：初始化页面html字体大小
说明： 最好在body加载之前执行
*/
var htmladapt = {
opt:{
design_w:720,
maxW:0,
minW:0,
default_fz:100
},
htmlObj:document.getElementsByTagName('html')[0],
init:function (option){
var self = this;
this.extend(this.opt,option);
this.setHtmlFontSize();

    window.addEventListener('resize',function(){
        self.setHtmlFontSize();
    },false)
},
setHtmlFontSize:function(){
    var opt = this.opt,fz;
    var base = win_width = window.outerWidth;

    if(opt.maxW && win_width > opt.maxW){//最大值
        base = opt.maxW;
    }
    if(opt.minW && win_width < opt.minW){//最小值
        base = opt.minW;
    }

    fz = (base/opt.design_w)*opt.default_fz;
    this.htmlObj.style.fontSize = fz+'px';
},
extend:function(o,n){
    for(var p in n){
        if(n.hasOwnProperty(p) || !o.hasOwnProperty(p)){
            o[p]=n[p];
        }
    }
},
getStyle:function(obj, attr) {
    return obj.currentStyle ? obj.currentStyle[attr] : getComputedStyle(obj,false)[attr];
}
}

用法
htmladapt.init({design_w:720,maxW:720, minW:320});
求指教
