### ISSUE TITLE
flexible有禁止横屏的方案么？

### ISSUE THREAD

**Issue by andorcba** [amfe/lib-flexible#23]
在尝试使用flexible之后发现非常好用。但是在有些项目中，不希望页面支持横竖屏切换。请问，这要怎么办？

**Comment by janmi** [comment]
可以通过监听横竖屏的切换来调整布局！

**Comment by YunyChan** [comment]
有些浏览器是不能禁止横屏切换的，建议放弃这种禁止切换的方案。
应该去适应屏幕切换后的分辨率才是的最佳选择
