### ISSUE TITLE
designUnit - 设计稿最小单位a（以px为单位）这个最小单位是怎么定的，我看代码里面， var ratio = designUnit / designWidth * 10;所有的宽度都是以这个为基准值的。一直看不懂，能不能麻烦给为说一下？

### ISSUE THREAD

**Issue by prp632791853** [amfe/lib-flexible#24]

**Comment by airen** [comment]
最小单位其实就是一个`a`，而这个`a`就是视窗宽度的`1/100`（也就是相当于`1vw`）。这样就把设计图分面了`100`等份，每一个等份就是一个`a`。为了更好的计算,`1rem`被认为是`10`个`a`。如此一来，假设设计稿尺寸为`750px`，那么：

```
1a   = 7.5px
1rem = 75px 
```

[#17](https://github.com/amfe/article/issues/17)
