### ISSUE TITLE
IOS设备上 border会渲染出不一致的结果

### ISSUE THREAD

**Issue by fwon** [amfe/lib-flexible#27]
在iphone5s等高清屏上，dpr为2， scale为0.5。发现有些横向的border, 如border-bottom, border-top定义为1px的时候， 会渲染出不一样的大小，滑动屏幕的时候border也会出现闪烁现象。

**Comment by iceshu** [comment]
同问我也是这个问题，我的解决方案就是在左右一边加个线 就能渲染的好点

**Comment by njleonzhang** [comment]
遇到同样问题，求解决方案

**Comment by njleonzhang** [comment]
已经没人维护了么？

**Comment by airen** [comment]
使用的时候border单位是用的px还是rem？

**Comment by fwon** [comment]
最开始是用rem，现在加了/*no*/保持px单位就不会闪了。1px对应的rem在某些机子上不显示，比如魅族。

**Comment by njleonzhang** [comment]
@fwon 能详细解释下这句么？
`
 现在加了/no/保持px单位就不会闪了
`

**Comment by fwon** [comment]
@njleonzhang 就是不把px转换成rem单位，保持1px

**Comment by njleonzhang** [comment]
@airen @fwon  border没用过rem做单位啊。一直是px哦

**Comment by Angelkuga** [comment]
用1px的时候  新的处理方式  ios9以上是  按1倍屏处理  6plus上面  实际占用的物理像素就是3  border线看起来明显很粗。 为什么要单独对 ios9以上的做 1倍处理 我很不明白

**Comment by fwon** [comment]
@Angelkuga 实际上 initial-scale 不是已经进行了缩小操作吗，所以1px应该不会看起来是3px吧

**Comment by Angelkuga** [comment]
@fwon  其实我想知道  【针对OS 9_3的UA，做临时处理，强制dpr为1，即scale也为1，虽然牺牲了这些版本上的高清方案，但是也只能这么处理了】 为什么要这样做  正常按dpr为3 显示会有什么问题

**Comment by ckrad** [comment]
同问 我也遇到了这个问题 很多有边框的元素渲染出来很丑 不知道是否有解决方案 或者谁能解释一下具体是什么原因造成这种情况

**Comment by njleonzhang** [comment]
不知道各位遇到的和我是不是一个问题，ios上border会被下面的元素盖住，有时候看起来细了，有时候甚至看不见了  https://github.com/amfe/lib-flexible/issues/72

**Comment by suface** [comment]
1px 如果需要，建议用css3写；参考 阿里去啊的 ，[移动端 Retina屏 各大主流网站1px的解决方案](http://www.cnblogs.com/surfaces/p/5158582.html)
