### ISSUE TITLE
Android bug

### ISSUE THREAD

**Issue by ximan** [amfe/lib-flexible#3]
分2种，A：栅格对不齐，B：错位。
A：小米1/系统4.4/UC；魅族MX2/QQ、UC；HTC/系统2.3/UC
B：魅族MX2/自带浏览器；HTC/系统2.3/QQ

**Comment by ximan** [comment]
按道理你们应该也会遇到这个bug吧
《Mac下Chrome手机模拟器里网页字号bug》
http://segmentfault.com/q/1010000002505938

**Comment by wintercn** [comment]
栅格对不齐是四舍五入问题，错位是某些浏览器丢掉了rem的小数部分…… 是已知问题，没啥办法，现在只能wont fix。

**Comment by wintercn** [comment]
字号bug，应该是这个文章说的原因吧 https://github.com/amfe/article/issues/10
