### ISSUE TITLE
基于lib-flexible开始过程中出现字体渲染混乱

### ISSUE THREAD

**Issue by andorcba** [amfe/lib-flexible#33]
场景：
我可能有个li列表，每个列表项的布局是相同的，只是文字差异，我完成了一个的时候 字体设置都没有问题。但是当我copy这个布局重复写入到页面里后，页面里所有的文字字号都变大了。

这是什么引起的？ 我排查了dom和样式都没感觉是因为布局或样式导致的。求大神帮忙排查下。

**Comment by miyagyh** [comment]
同问，我今天也遇到了这样的问题。检查了dom和样式感觉也没有问题。不知道在哪里出错了。

**Comment by nkCoding** [comment]
检查一下是不是触发了 Webit 的 font-boosting

**Comment by andorcba** [comment]
@nkCoding   非常给力，就是这个问题。问题已经解决了~
