### ISSUE TITLE
布局缩放

### ISSUE THREAD

**Issue by rocky-191** [amfe/lib-flexible#36]
用了flexible后，在小米手机上弹出键盘后，缩放比例会重新计算一次，导致布局发生变化。是否可以只计算一次缩放比例，或者有没有别的解决办法。另外在华为手机上上下移动屏幕都会重新计算缩放比例，导致布局变化，是否有解决办法

**Comment by dd1994** [comment]
我在小米 4c 上测试是正常的

**Comment by dd1994** [comment]
我看他代码重新计算缩放比例是绑定在 `window.resize` 和 `window.pagehow` 上面的，你要看看是否触发了这两个事件。

**Comment by rocky-191** [comment]
恩，后来我把那两个事件注释了，不让执行
