### ISSUE TITLE
华为荣耀的微信webview省略了rem小数点后面的数字

### ISSUE THREAD

**Issue by ccsang** [amfe/lib-flexible#37]
获取视口的宽度和dpr都是正确的。页面的右边却出现一大段空白，怀疑是rem出问题了

**Comment by Tomatoo** [comment]
我在魅蓝的微信浏览器下面测试的时候，也发现了rem布局表现怪异，还没找到解决方案。Google之后得到rem在某些机型的微信浏览器下面布局会存在bug，但是不知道是哪些机型。

**Comment by ccsang** [comment]
小米4 华为荣耀的 Android webkit 也有这个问题。

**Comment by dd1994** [comment]
你倒是搞个 demo
