### ISSUE TITLE
viewpor 缩放比例为什么安卓下的所有设备都是1倍？

### ISSUE THREAD

**Issue by ystarlongzi** [amfe/lib-flexible#4]
如题，在安卓下设置缩放比例始终为1倍，为什么要采取这种策略呢？
如果安卓下某设备的 devicePixelRatio 是2 或 3 呢？

**Comment by rockcoder23** [comment]
同问~  假如我参照iPhone开发。那么在iPhone上字体是对的，比如设置了(28px) 。 那再安卓机子上就字体特别大，因为安卓dpr都是1来处理的。请问是怎么解决的

**Comment by wintercn** [comment]
这个主要是因为之前Android的dpr不少都是假的，新版本已经修正

**Comment by youngwind** [comment]
@wintercn 新版本已经修正了？那为什么现在代码里面的还是把所有安卓设备dpr都设置为1呢？
