### ISSUE TITLE
为什么不建议字体使用rem，并且为什么不直接将设计稿的尺寸除以一百来达到同样的效果呢

### ISSUE THREAD

**Issue by jasonChen1982** [amfe/lib-flexible#42]
为什么不建议字体使用rem，字体使用rem会照成什么问题吗？并且为什么不直接将设计稿的尺寸除以100，并通过计算相应的根font－size来达到同样的效果呢？

**Comment by jasonChen1982** [comment]
这个不需要吧，因为rem自适应之后在不同的屏幕上的实际位置都是不一样的，如果在宽屏幕上字体也用px岂不是会使得字体显得比较小，和设计稿的原始整体比例不一致了？

**Comment by eyeA** [comment]
个人感觉手机端用rem会比较好吧，看官方api没有合适的解释

**Comment by darren562** [comment]
用rem 字体会出现小数 如 17.666px 等，字体会模糊

**Comment by jasonChen1982** [comment]
我们项目里面字体也用rem，然而并没有说出现模糊的情况😄

**Comment by yzg1943** [comment]
字体用px，电脑上模拟没问题，手机上访问，傻大甚至给布局都撑开了....
