### ISSUE TITLE
OS 9_3遇到什么坑呢

### ISSUE THREAD

**Issue by chen--johnny** [amfe/lib-flexible#43]
OS 9_3遇到什么坑呢，能详细说说么

**Comment by dawnwish** [comment]
http://stackoverflow.com/questions/33618595/ios9-safari-viewport-issues-meta-not-scaling-properly
https://forums.developer.apple.com/thread/13510
http://www.wmyl.se/en/blog/safari-ios-9-causing-issues-responsive-sites/
