### ISSUE TITLE
总是遇到 Chrome 开发工具 mobile 模式样式会有问题

### ISSUE THREAD

**Issue by NextSeason** [amfe/lib-flexible#50]
如题。不知道大家有没有遇到过。我这里频率还比较高，看起来是字号出问题。一般情况下重启浏览器会好。

**Comment by BrotherBB** [comment]
表示也一样遇到过，chrome里开启手机模拟之后，chrome实际上计算出来的字体大小与样式不一致，偏大了

**Comment by banbanchs** [comment]
Font Boosting https://github.com/amfe/article/issues/10
