### ISSUE TITLE
菜鸟的一个代码疑惑

### ISSUE THREAD

**Issue by Mrwei12345678** [amfe/lib-flexible#52]
window['lib']代表什么

**Comment by yuchuanxi** [comment]
从全局作用域取lib变量


我觉得你需要去学习下js

**Comment by njleonzhang** [comment]
@yuchuanxi 你的回答好伤人  :)

**Comment by yuchuanxi** [comment]
@njleonzhang 额，不过这个确实算很基础了

**Comment by Mrwei12345678** [comment]
@yuchuanxi 我确实很菜啦，顺便问一下，我并没有在flexible.js里发现有lib全局变量啊，求高手解答

**Comment by yuchuanxi** [comment]
@Mrwei12345678 避免重复定义
`window['lib'] || (window['lib'] = {})`如果lib已经定义（window['lib']能获取到），就传这个`lib`
如果没有定义就给`lib`赋值空对象，并传入`lib`

这个时候在flexible.js里面的`lib`其实就已经是`window.lib`了（js中对象按引用传递）

**Comment by njleonzhang** [comment]
@Mrwei12345678 借你的帖子问几个问题
@yuchuanxi 
* 这个项目还维护么？好久不更新了。
* ios9.3的问题彻底解决了么？
* 我们微信项目用了这个库，很喜欢？另外也有一个痛点：ios浏览器里面rem除不尽的时候，有时候会导致一些bug（例如: 我们项目的这个页面，在iphone5上打开的时候一些border就不见了[找人上门](http://www.51zrsm.com/static/wx/index.html#!/maintain_index)）。这个问题有解决方案么。

**Comment by codekissyoung** [comment]
@njleonzhang 我看你项目，不论什么终端，dpr都是1啊！

**Comment by airen** [comment]
@njleonzhang 项目还在维护的。而且这个项目在手机淘宝使用率是非常高的。

**Comment by codekissyoung** [comment]
@airen 大漠老师，里面的对于
```
        if (width / dpr > 540) {
            width = 540 * dpr;
        }
```
的考虑是什么呢？

**Comment by codekissyoung** [comment]
@njleonzhang 你是不是自己在项目里面直接写的
```
<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
```
而不是动态生成的啊？

**Comment by njleonzhang** [comment]
@codekissyoung 是的。我们用了类似的做法，放弃了缩放。
主要原因有2个：
1. 我们这个是微信公众号，有一些页面有二维码，客户长按二维码，就可以关注我们的公众号，但是如果用了缩放方案，在微信里二维码识别会有bug（微信长按二维码识别好像是通过截屏实现的，页面scale之后，微信识别发生错位，是有问题的）。
2. 看到了文档里说ios9.3有bug，然后dpr已经全改成了1。

```
针对OS 9_3的UA，做临时处理，强制dpr为1，即scale也为1，虽然牺牲了这些版本上的高清方案，
但是也只能这么处理了
```

出于上面的考虑，我们就暂时偷了懒，把dpr都设置为1了。
按照文档我们做了这样设置：
`    <meta name="flexible" content="initial-dpr=1" />
`
最大的坏处就是1px solution没有了，ios上看，1px的border看起来会比较粗，丑了点。。。

所以我在问了这些问题啊：
@airen 老师能回答下我另外2个问题么？你出现了怎么就回答1个问题。

* ios9.3的问题彻底解决了么？
* 我们微信项目用了这个库，很喜欢？另外也有一个痛点：ios浏览器里面rem除不尽的时候，有时候会导致一些bug（例如: 我们项目的这个页面，在iphone5上打开的时候一些border就不见了。border消失的页面的连接：[找人上门](http://www.51zrsm.com/static/wx/index.html#!/maintain_index)）。这个问题有解决方案么。

**Comment by njleonzhang** [comment]
@codekissyoung 你的这个问题，我好像看到过解释，540貌似只是一个经验值，而且这个solution也没有为ipad设计，所以我觉得宽度大于540的设备上就别用这个solution了。实际也是如此，你在手机上的这个样式确实好看，但是如果将这个样式按比例放大到ipad这样的屏上可能就难看了。如果你确实想让540以上的设备按比例缩放，你把这断代码删了好了。这是我个人的理解啊，如果大神能出来帮你解释下就更好了。
