### ISSUE TITLE
ios使用scale后，调用高德地图，地图也会被缩掉，怎么解决？

### ISSUE THREAD

**Issue by Lee908105576** [amfe/lib-flexible#54]

**Comment by codekissyoung** [comment]
@Lee908105576 来点代码！！！

**Comment by Lee908105576** [comment]
@codekissyoung  比如这个小demo
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>MapApi</title>
  <style>
    #map{
      width: 100%;
      height:5rem;
    }
  </style>
</head>
<body>
<div id="map"></div>
<script src="build/flexible_css.debug.js" charset="utf-8"></script>
<script src="build/flexible.debug.js" charset="utf-8"></script>
<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4fba4eea391d2a1aba757a13516fa217
"></script>
<script type="text/javascript">
var map = new AMap.Map('map', {
        resizeEnable: false,
        zoom: 15,
        dragEnable: false,
        zoomEnable: false,
        center: [116.39, 39.9]
      });
      var marker = new AMap.Marker({
        position: [116.499084, 39.978931]
      });
      marker.setMap(map);
      map.setCenter(marker.getPosition());
</script>
</body>
</html>
`

**Comment by Lee908105576** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>MapApi</title>
  <style>
    #map{
      width: 100%;
      height:5rem;
    }
  </style>
</head>
<body>
<div id="map"></div>
<script src="build/flexible_css.debug.js" charset="utf-8"></script>
<script src="build/flexible.debug.js" charset="utf-8"></script>
<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4fba4eea391d2a1aba757a13516fa217
"></script>
<script type="text/javascript">
var map = new AMap.Map('map', {
        resizeEnable: false,
        zoom: 15,
        dragEnable: false,
        zoomEnable: false,
        center: [116.39, 39.9]
      });
      var marker = new AMap.Marker({
        position: [116.499084, 39.978931]
      });
      marker.setMap(map);
      map.setCenter(marker.getPosition());
</script>
</body>
</html>

**Comment by Lee908105576** [comment]
@codekissyoung 

`<body>
<div id="map"></div>
<script src="build/flexible_css.debug.js" charset="utf-8"></script>
<script src="build/flexible.debug.js" charset="utf-8"></script>
<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4fba4eea391d2a1aba757a13516fa217
"></script>
<script type="text/javascript">
var map = new AMap.Map('map', {
        resizeEnable: false,
        zoom: 15,
        dragEnable: false,
        zoomEnable: false,
        center: [116.39, 39.9]
      });
      var marker = new AMap.Marker({
        position: [116.499084, 39.978931]
      });
      marker.setMap(map);
      map.setCenter(marker.getPosition());
</script>
</body>`

**Comment by Lee908105576** [comment]
`<div id='map'></div>`

**Comment by Lee908105576** [comment]
`<div id="map"></div>
<script src="build/flexible_css.debug.js" charset="utf-8"></script>
<script src="build/flexible.debug.js" charset="utf-8"></script>`

**Comment by shinyChen** [comment]
链家网手机版就遇到了这个问题，采取的方案是：对于地图进行zoom，比例为dpr。[链接地址](http://m.lianjia.com/bj/map/pos/?pos=116.330198,40.074228&house_code=BJCP92166073)
scale当时没试过，理论上可以，但是是从中心点开始，需要transform-origin: 0 0 0。
还是zoom简单，不用写前缀，一个属性搞定。

**Comment by NextSeason** [comment]
@shinyChen 拖动的时候还是存在问题。

**Comment by shinyChen** [comment]
贴个链接吧，拖动的时候存在什么问题？拜托说得清楚点，要不怎么帮你解决问题

**Comment by changfuguo** [comment]
我用百度地图api也遇到这个问题，做法就是手动设置meta 设置为默认1，这个时候flexible就不会干预了

**Comment by pimkle** [comment]
@changfuguo 如果这样解决的话 这个页面其他的div 适配不会被打成原型吗？

**Comment by pimkle** [comment]
链接那个demo我看懂了。显示地图的那个页面关闭flexible。其他页面照样启用

**Comment by shiregg** [comment]
ios中，这是iphone6 <meta name="viewport" content="initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no">

 echarts整个都缩小了一半。

**Comment by songsiqi** [comment]
可以手动设置一下 viewport 不缩放， `<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">` 就可以了。但是会有个问题，1px 的线不细了

**Comment by 94dreamer** [comment]
如何手动设置

**Comment by 94dreamer** [comment]
@shinyChen  手机sacle之后 地图变模糊

**Comment by 66beta** [comment]
有个简单粗暴的办法：
1、在当前页面（组件），重置下meta标签和dpr
```
mounted () {
    this.$nextTick(function () {
      const dpr = document.documentElement.getAttribute('data-dpr')
      if (dpr > 1) {
        window.tempViewport = document.querySelector('meta[name="viewport"]').getAttribute('content')
        document.querySelector('meta[name="viewport"]').setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        window.tempDpr = dpr
        document.documentElement.setAttribute('data-dpr', 1)
      }
    })
  //.......
}
```
2、离开页面的时候，再还原回去：
```
beforeRouteLeave (to, from, next) {
    if (window.tempViewport) {
      document.querySelector('meta[name="viewport"]').setAttribute('content', window.tempViewport)
      delete window.tempViewport
    }
    if (window.tempDpr) {
      document.documentElement.setAttribute('data-dpr', window.tempDpr)
      delete window.tempDpr
    }
    next()
}
```
3、覆盖地图组件的样式

如果不用vue-router的话，可以用mixins
