### ISSUE TITLE
iOS input type = radio scale 选中样式不能看

### ISSUE THREAD

**Issue by NextSeason** [amfe/lib-flexible#55]
iOS input type = radio scale 选中样式不能看，有啥解决方案么？

**Comment by shinyChen** [comment]
能说得清楚点吗，是radio元素缩放的时候样式有问题还是？我理解选中样式不能看应该和flexible没关系吧，如果觉得难看可以用js模拟一个radio元素出来，类似于百度新闻http://news.baidu.com/
