### ISSUE TITLE
以后这个 flexible 会考虑使用 vw 代替吗？

### ISSUE THREAD

**Issue by dd1994** [amfe/lib-flexible#57]
用 vw 为单位做适配看上去相当完美，也非常简单，由 flexible 迁移过去也很简单，现在微信的 x5 内核也支持了。唯一的缺点就是至少需要 安卓 4.4。所以以后这个 flexible 会考虑使用 vw 代替吗？

**Comment by mingelz** [comment]
其实 flexible 方案从设计时就是考虑到了 vw/vh 的，所以当可以大范围使用时也一定会跟进
