### ISSUE TITLE
rem是基于html根元素的font-size来转换还是根据设计稿的尺寸来转换

### ISSUE THREAD

**Issue by menglingbujie** [amfe/lib-flexible#59]
看了文章介绍，没有详细说明px2rem具体是根据根元素fontSize转还是根据设计稿转。
因为根元素的fontSize是变化的，less无法获取当前根元素的fontSize所以无法转。
目前只能用[px2rem](https://www.npmjs.com/package/px2rem)工具在gulp里初始化fontSize来转px2rem({remUnit:75})。
所以请说明一下这两个单位之间的具体转换方法

**Comment by airen** [comment]
这个分两种情况，你不需要关注浏览器渲染时，html元素的font-size是多少。你只需要在你的编辑器或者说你的配置文件中设置好remUnit，而这个remUnit是根据你的设计稿来定的。如果你的设计图是640px,那么remunit的值是64px;如果设计图是750，它的值是75px,依此类推。

在实际编码根据这个基本单位将px转换成rem。那么在客户端渲染的时候，就能达到所要的适配效果。建议看看这篇文章：
http://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html
