### ISSUE TITLE
字体大小为何不推荐用rem作为单位

### ISSUE THREAD

**Issue by luyujun** [amfe/lib-flexible#6]
如题，我字体大小用了rem，也没发现什么问题。

**Comment by 90arther** [comment]
flexible的主要就是通过屏幕伸缩屏幕，是根据屏幕计算出来的，如果字体出现rem，就有可能出现一些不寻常的尺寸，而现在很多字体文件自带点阵尺寸。

**Comment by sxqwaade** [comment]
我字体用了rem后 部分标签下的字体大小渲染不正确，比如基准大小为40px，p标签设置字体大小为0.7rem，如果显示正常的话 应该是28px，但是页面实际显示的却是38px，研究了很久 还是没有找到原因，谁能告诉我下吗？

**Comment by luyujun** [comment]
@sxqwaade , 基准大小40px需要设置到html上，测试了下没发现你说的问题
![image](https://cloud.githubusercontent.com/assets/1794881/9240495/a02d828e-4199-11e5-8cf9-e1528c7e774d.png)

**Comment by 329530588** [comment]
@sxqwaade 看下代码

**Comment by udbmnm** [comment]
@sxqwaade 毫无疑问，你肯定写错了

**Comment by sxqwaade** [comment]
原因找到了，是因为我在页面中已经设置了viewport，这导致在安卓的UC游览器中出现怪异的现象，去掉<head>标签中的viewport，完全由插件控制，就恢复正常了。

**Comment by wintercn** [comment]
@90arther 说的对，30px以下的字体，还是需要考虑点阵问题的。

如果是比较大个的文字，则不受限制。

**Comment by wintercn** [comment]
@sxqwaade  你遇到的问题听上去是font boost导致的，过几天我们可以放个文章出来讲讲

**Comment by hbrls** [comment]
@wintercn 字体的点阵问题仍然存在吗？知乎上的讨论 https://www.zhihu.com/question/20440679 好像并不能支持这个结论。

假如暂时不考虑用户自装字体主题的情况，只使用系统默认字体，我需要怎样确认是否会收到影响呢？
