### ISSUE TITLE
如何处理缩放之后 touch 事件的 screenX/screenY

### ISSUE THREAD

**Issue by meowtec** [amfe/lib-flexible#61]
在使用 touch 事件做滑动组件，通过两次 touch 的 screenX 差值移动 DOM 元素，但是拿到的 screenX 有问题。

在 iOS safari 里面，screenX 是 2x 的，触摸屏幕右侧时，screenX 大概是 640
而在 iOS webview 里面，screenX 是 1x 的，屏幕右侧的 screenX 是 320.

而他们的 window.screenWidth 都是 320

有没有解决办法？

**Comment by moyaoxiong** [comment]
flexible再html里面设置了data-dpr，iPhone6是2，试试screenX=screenX/data-dpr
或者增加监听事件
document.addEventListener('touchstart', touch, false);
document.addEventListener('touchmove', touch, false);
document.addEventListener('touchend',touch, false);
//touch为自己写的检测function

获取点击的坐标event.touches[0].clientX，event.touches[0].clientY

**Comment by meowtec** [comment]
@moyaoxiong 

这样没用。
仔细看我的描述，同一部手机，在 webview 和 safari 里面都按照 2 倍进行缩放，screenX 一个是 320，一个是 640. 

最后我的解决方式是用 pageY 代替 screenY。
