### ISSUE TITLE
6plus上的图片为什么会很小

### ISSUE THREAD

**Issue by liz282907** [amfe/lib-flexible#62]
最近用flexible,设置了具体宽高的元素会相应的缩放，但是对于大小不定的图片，没有办法设置宽高，然后在6plus上图片显示的很小，请问有解决的方法不..而且横屏的时候font-size为啥是180px...

**Comment by moyaoxiong** [comment]
图片宽度用百分百吧，横屏时触发onresize事件，会根据横屏宽度重新设置font-size，你是1080p的屏就设置180px

**Comment by airen** [comment]
对于这样的现象，最好是能附上对应的代码或者在线的测试DEMO。不然很给想像出，也不好排查相关问题。
