### ISSUE TITLE
动态设置viewport的scale后导致app里webview的页面无法左右滑动

### ISSUE THREAD

**Issue by dongweb** [amfe/lib-flexible#63]
动态设置viewport的scale后导致app里webview的页面无法左右滑动，有没有遇到同样问题的？

**Comment by moyaoxiong** [comment]
viewport已设置了不能缩放，不知道你的左右滑动是类似swiper的切换图片，还是整页滑动。

**Comment by dongweb** [comment]
是整页滑动

**Comment by geraldlrh** [comment]
+1 ios下4.7寸的屏幕不能整页滑动了，但其他尺寸可以，略诡异

**Comment by midi-zeng** [comment]
不是动态设置的问题，scale缩放比为0.5时，会导致无法左右滑动，应该是缩放也会监听touch事件，这个0.5的特殊场景跟原生的冲突了
