### ISSUE TITLE
华为p8 自带浏览器rem有问题，好像被四舍五入了，怎么解决？

### ISSUE THREAD

**Issue by hanzhenlong** [amfe/lib-flexible#64]
![image](https://cloud.githubusercontent.com/assets/11323590/16407814/3d67e134-3d48-11e6-96c1-2394df7a4f3a.png)

我用华为p8 自带浏览器看了一下，手淘的首页是这个样式，是为了解决什么问题，做成这样的吗？

**Comment by hanzhenlong** [comment]
![image](https://cloud.githubusercontent.com/assets/11323590/16407742/e1f4c880-3d47-11e6-8f40-490883e69188.png)

我看了一下，手淘的首页是这个样式，是为了解决什么问题，做成这样的吗？

**Comment by westfall1990** [comment]
安卓自带的浏览器兼容性问题很多啊。别的浏览器也是着吗？

**Comment by hanzhenlong** [comment]
@westfall1990 别的还没碰到过，我也是首次在项目中用

**Comment by fly-studio** [comment]
华为的 即使$('html').attr('style', 'font-size:36px!important'); 
得到的还是31px
