### ISSUE TITLE
横屏的页面可以做到吗

### ISSUE THREAD

**Issue by flyer153** [amfe/lib-flexible#65]
视觉稿大小分为640，750以及，1125这三种，那么如果我做横屏时width为1136的页面可以自适应吗？

**Comment by flyer153** [comment]
已经自己解决，O(∩_∩)O谢谢

**Comment by cty8998** [comment]
@flyer153 我觉得应该是没问题的，因为你以1136标准开发，换算到其他比率结果是一样的。都是按1136的rem等比换算成其他分辨率的尺寸

**Comment by flyer153** [comment]
@cty8998 哈哈，感谢，亲测了一下，发现没什么问题！

**Comment by whidy** [comment]
@flyer153 你是怎么处理的,用了px2rem的插件吗...比如750的设计稿,我设置remUnit: 75;那么正常满屏是10rem,很OK
但是将iPhone6横屏就会出现无法占满整屏的情况了.
