### ISSUE TITLE
请问下手淘的这个方案不支持横屏的切换和ipad吗？

### ISSUE THREAD

**Issue by se7en-1992** [amfe/lib-flexible#66]
请问下手淘的这个方案不支持横屏的切换吗？我这2天研究了下，做了一个简单的demo发现在横屏切换或者在ipad下这个方案是不行的

**Comment by flyer153** [comment]
@se7en-1992 和横竖屏没关系，都可以！不知道你说的方案不行具体指的什么？

**Comment by super2457** [comment]
@flyer153 `b / i > 540 && (b = 540 * i)` 这段代码把字体最大限制为540 / 10， 54， 在 ipad 下 54px大font-size，导致了rem不准，请问是因为我`<meta name="flexible" content="initial-dpr=2,maximum-dpr=3" />`导致的？其实不用去掉这段代码 `b / i > 540 && (b = 540 * i)` ，又或者这段代码的意义是?

**Comment by airen** [comment]
这个lib是不支持横屏和ipad，而且在这篇文章中http://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html 也介绍过，不适合iPad和PC。另外关于横屏，主要是因为手机淘宝的业务不需要支持横屏。

**Comment by Gaohaoyang** [comment]
这还真是个坑……今天我也遇到了 @super2457

**Comment by zcoding** [comment]
才看到。。。难怪最大54
