### ISSUE TITLE
感觉这个项目已经被原作者抛弃了。据说淘宝内部有更好的解决方案，只是没有开源出来，是这样的吗？

### ISSUE THREAD

**Issue by westfall1990** [amfe/lib-flexible#67]

**Comment by super2457** [comment]
+1

**Comment by airen** [comment]
这个项目并没有抛弃，我们内部很多团队都在使用。你所说的更好的解决方案不知道是不是指的weex。如果是的话，你也可以尝试使用weex，而且weex也开源了。

**Comment by DoranYun** [comment]
前端所有东西都是开源的，打开淘宝，用 Chrome Devtools 看一下不就知道了，很多项目还是在用 flexible 啊。
