### ISSUE TITLE
设计稿到rem转换

### ISSUE THREAD

**Issue by ceemomx** [amfe/lib-flexible#7]
设计稿42像素除以基准font-size:36 得到1.16rem 但是在webapp里 实际上看起来要比设计稿宽很多

**Comment by wintercn** [comment]
这得看你设计稿的宽度吧？

**Comment by dawncold** [comment]
计算时是否需要考虑scale？

**Comment by mingelz** [comment]
@dawncold 不需要。
举例：
* 设计稿整体宽度：640px
* 稿中的某个元素宽度：42px

使用 flexible 时，页面整体宽 10rem，也就是 1rem = 64px，那么稿中元素应该：`44px / 64px = 0.6875rem`。

你的例子中，`font-size: 36` 表示设计稿整体为 360px 宽。如果实际设计稿宽度不为 360px，则不应该除 36。

**Comment by airen** [comment]
@dawncold  可以看看篇[教程](https://github.com/amfe/article/issues/17)

**Comment by Bantes** [comment]
@mingelz 有没有办法自动计算rem的啊？每次都得去px到rem转换好烦躁 ...

**Comment by dawncold** [comment]
@Bantes 你如果用LESS或者SASS的mixin能自动算，估计taobao也是用的这种

**Comment by mingelz** [comment]
@Bantes @dawncold 其实方法还是挺多的。举几个例子：

* @flashlizi 写了一个 sublime 的代码提示工具，写 `75px` 时，直接提示 `1rem`。不过这个方案原始值没有被保存，后期不好维护。

* 用 sass：
    ```sass
    $rem: 75px;
    @function px2rem($px) {
      @return $px / $rem * 1rem;
    }

    div {
      width: px2rem(150px);
    }
    ```
这个方案的缺点也很明显，破坏了原来的书写习惯，所有的值都要使用 px2rem 转。

* 这是我们现在正在使用的方案：@songsiqi 同学开发了 [px2rem](https://www.npmjs.com/package/px2rem) 工具，源码中正常写 px 值，最后通过 gulp 等工具自动处理为 rem 单位。方便快捷无成本，居家旅行必备。

**Comment by dawncold** [comment]
@mingelz 现在前端都流行用nodejs在上线前做一些预处理吧？比如less转css，再压缩合并等等

**Comment by mingelz** [comment]
@dawncold 第3个方案就是。px2rem 已经提供了 gulp/webpack/postcss 等版本。

**Comment by luzhilin** [comment]
@mingelz 赞。请问，你们使用flexible后icon是怎么解决的
