### ISSUE TITLE
关于应用lib-flexible的图片适配问题

### ISSUE THREAD

**Issue by myseawp** [amfe/lib-flexible#70]
@airen 请教下使用lib-flexible的图片适配问题

flexible文档只描述布局适配，没有说明如何实现图片适配。

我从另一篇文章里看到 [](https://github.com/amfe/article/issues/8)
使用img4dpr 根据dpr编译css，生成对应的图片地址：

![image](https://cloud.githubusercontent.com/assets/13513205/17423394/ecc3b984-5aec-11e6-8e98-21cebe671290.png)

![image](https://cloud.githubusercontent.com/assets/13513205/17423555/0d44961e-5aee-11e6-9c1c-49515bf1592f.png)

但由于Flexible针对Android设备 dpr全都默认是1，是否Android设备全放弃高清图方案，使用375px的图片规格？

![image](https://cloud.githubusercontent.com/assets/13513205/17423540/ebc31d1c-5aed-11e6-852e-62ca1fec2e52.png)

这是我搜到的主流Android手机物理分辨率，如果只按照非高清图来画页面，不会导致显示模糊么 ？

我自己理解的图片适配方案是不按dpr来匹配图片，只根据设备分辨率计算，如果大于750px，就只用3x高清图，大于375就只用2x高清图，其他的就用1x的图。

是否是我理解有误，还请指教！

另外，文档中提到的类库：img4dpr与lib.img 是否开源？

**Comment by airen** [comment]
img4dpr对应的lib.img并没有开源。但在网上有类似的解决方案，可以自己查一下相关资料。感觉你这个图片的读出，是不是更应该考虑根据不同的设备在CDN上获取不同的尺寸呢？不知道这篇文章对你是否有一定的帮助：https://github.com/amfe/article/issues/8
