### ISSUE TITLE
用了rem之后 很多元素的边线粗细不一样 这个是为什么

### ISSUE THREAD

**Issue by ckrad** [amfe/lib-flexible#75]
用了rem之后 很多元素的边线粗细不一样 这个是为什么

**Comment by njleonzhang** [comment]
不知道你遇到的和我是不是一个问题，ios上border回被下面的元素盖住，有时候看起来细了，有时候设置看不见了  https://github.com/amfe/lib-flexible/issues/72

**Comment by suface** [comment]
1px 如果需要，建议用css3写；参考 阿里去啊的 ，[移动端 Retina屏 各大主流网站1px的解决方案](http://www.cnblogs.com/surfaces/p/5158582.html)
