### ISSUE TITLE
内嵌再微信公众号内出现bug

### ISSUE THREAD

**Issue by joker-danta** [amfe/lib-flexible#76]
我在做一个关于微信公众号的时候出现bug。
原因是动态生成的meta标签并没有指定width=device-width，会导致页面出现横向滚动，既然作者有去动态计算缩放比，我觉得作者必然不会是忘记了或者不知道，所以请教一下，为何我在使用的时候会出现横向的滚动，但是当我添加了width=device-width了就好了。有兴趣的话 可以在qq浏览器中测试一下，谷歌苹果等浏览器是正常的

**Comment by alongchengtian0** [comment]
动态缩放比跟width=device-width是两种不同的机制，
1.iOS，Android等移动端设备，的meta标签viewport 会引发WebView对于屏幕尺寸进行计算以适配不同的移动端屏幕(同样的100px在有无标签两种情况下页面的显示也是不一样的)
   [Android](https://developer.android.com/guide/webapps/targeting.html) iOS设备也类似
2.lib-flexible 库是给整个布局部分提供了一个基础的限定，然后在整个基础上布局。

总之在移动端设备上适配，是必须要加width=device-width的。原因看上面安卓那篇文章就知道了。

**Comment by joker-danta** [comment]
按照你说的lib-flexible.js是提供了基础的限定，那么在移动端开发（不是APP）的时候其实是需要自己去添加width=device-width的吗？

**Comment by alongchengtian0** [comment]
@joker-danta 是的需要自己添加width=device-width
