### ISSUE TITLE
发现在这种方案中，display:block会使字体过大，必须给出inline-block才会好

### ISSUE THREAD

**Issue by wy2016xiao** [amfe/lib-flexible#78]
这是怎样一个原理呢。。。
而且在苹果手机上预览不需要给inline-block，字体大小正常，但在安卓和chrome上面显示的时候就会过大，必须给出inline-block才会正常

**Comment by Jogiter** [comment]
+1

**Comment by channg** [comment]
＋2

**Comment by iceshu** [comment]
```CSS

body, #root {
    width: 10rem;
    max-height: 1000000px; //这事重点
    background: #f3f5f9;
    overflow-x: hidden;
}
``` 试试

**Comment by crowphy** [comment]
这个问题直接原因是由元素没有指定高度引起的，根本原因是因为触发了webkit内核浏览器的Font Boosting特性，通过设置该元素的高度或者给body指定个max-height可以避免触发该特性。

**Comment by airen** [comment]
请更换新的布局适配方案：https://www.w3cplus.com/css/vw-for-layout.html
