### ISSUE TITLE
对于已用第三方开源UI框架的项目，如何改造

### ISSUE THREAD

**Issue by bigmeow** [amfe/lib-flexible#80]
这种开源UI框架内部都是用px，em单位，适合用lib-flexible来改造么？我直接用你们提供的gulp插件把UI框架转换成rem单位后，界面就变得很奇怪了，比如像bootstrap,framework7这种框架

**Comment by zwsf** [comment]
同问，不太明白为什么框架都在使用px em 百分比，而不是rem单位，有高手指点一下嘛？

**Comment by huangfeng02** [comment]
我也想知道呀  我项目中想引入sui框架 那里有很多现成的控件 比如 时间 日历 弹窗 但是引入后样式冲突呀

**Comment by EasonZhang2015** [comment]
我目前的解决方案是放弃高清方案，所有设备dpr都为1，这样就可以使用其他ui框架和组件了。至少尝试过重写ui框架的css源码，但是最头疼的事情是，很多组件的样式同时也用js控制的，所以只能出此下策。希望能有更好的方案。

**Comment by zhu353071655** [comment]
兼容第三方ui组件是个头疼的问题

**Comment by airen** [comment]
简单一点的改造方法就是将第三方的UI组件中使用了`px`做单位值的地方，想办法将其转换为`rem`单位。至于怎么更好的转换，你可以写个PostCSS的插件。

**Comment by EasonZhang2015** [comment]
@airen  postcss自然是能将px转成rem的，问题在于很多组件不支持rem这个单位。

**Comment by airen** [comment]
@EasonZhang2015 不明白什么叫组件不支持`rem`这个单位。支不支持`rem`不是由组件来决定的，而是由你的客户端来决定的。

**Comment by EasonZhang2015** [comment]
@airen 刚才说错了，不支持rem单位的不是组件，而是一些html5+的api，比如设置webview高度的api。我跑偏了，主要还是问如果要写postcss的话，是将组件中无论css还是js中的单位都转换成rem吗？

**Comment by airen** [comment]
@EasonZhang2015 原则上就是把除了`font-size`之外的地方使用的`px`转换成`rem`。然后在使用了`font-size`的地方，通过`[data-dpr="2"]`和`[data-dpr="3"]`重置`font-size`的值。

**Comment by EasonZhang2015** [comment]
@airen 举个例子，如果组建里的某个值是变量，如下：`var a = b + 'px';`，这个时候就没法转rem了。而且组件中的宽高经常通过计算获得，而还有一些则是百分比，这时候就无法转rem了。另外还有个问题请教，现在安卓设备统一设置dpr=1是放弃了安卓设备的高清效果了吗？
