### ISSUE TITLE
字体不走rem,而是通过gulp相关插件实现

### ISSUE THREAD

**Issue by kiven1989** [amfe/lib-flexible#83]
怎样通过gulp的postcss-px2rem  就实现字体px不被转换成rem,  而不是通过/_px_/  这个种手动方式实现呢?

**Comment by weizs** [comment]
postcss-px2rem不是有一个propWhiteList么，指定转换部分属性，当然这也可能麻烦点，所以postcss-px2rem作者又改成了propList，不过我看他没有合并到master并发布到npm，所以自己fork后重新发布了个postcss-px2rem-plus，自己用上了最新的

**Comment by eltonchan** [comment]
用sass

@mixin px2px($px){
  [data-dpr="1"] & {
    font-size: ($px / 2) * 1px;
  }
  [data-dpr="2"] & {
    font-size: $px * 1px;
  }
  [data-dpr="3"] & {
    font-size: ($px / 2 * 3) * 1px;
  }
}

**Comment by weizs** [comment]
@kiven1989 [楼上说的和你问题貌似不符，你直接用新版的postcss-px2rem(https://github.com/weizs/gulp-pxtorem-plus.git)，不希望转换的就加忽略或者写成大写PX

**Comment by airen** [comment]
文章中有详细介绍过这一部分：http://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html
