### ISSUE TITLE
宽度使用10rem，在部分手机webview中未全屏。

### ISSUE THREAD

**Issue by jkcaptain** [amfe/lib-flexible#84]
插件真的很好用，解决了好多页面适配的问题。谢谢你们。
但是，在做app产品内的网页时发现，
在红米2a，和三星note5的webview中，10rem不会全屏
红米2a中，如果宽度写10rem会超出，
三星note5中，如果宽度写10rem，宽度会铺不满一屏。
但是在这2款手机的自带浏览器中浏览时，页面正常。
目前仅在这2款手机中发现问题。

**Comment by jkcaptain** [comment]
追问，是因为没写device-width的原因吗

**Comment by syd2011** [comment]
同样遇到 在pad端会出现10rem不等于全屏的问题

**Comment by jkcaptain** [comment]
pad端和PC端是不会全屏的，我估计是因为，在pad端dpr是设为1，然后flexible.js里面有一段代码是，
if (width / dpr > 540) {
        width = 540 * dpr;
 }
说明dpr为1的情况下，最大宽度就是540PX吧。
三星note5手机不会全屏，我估计也是这个原因。
可以红米2a，10rem超出了一屏，我就找不到原因了,可能是因为红米辣鸡吧。。。

**Comment by syd2011** [comment]
谢谢啦，你们网页在chrome里用emulated device模拟红米会出现超出10rem的情况吗？
原来我们做在微信公众号里的网页虽然不是红米2a 但是小米手机没有出现超出10rem的情况

**Comment by jkcaptain** [comment]
不是模拟，是红米2a真机。系统版本是安卓4.4.4。

**Comment by zhu353071655** [comment]
据说有些安卓机获取innerWidth不准确，会导致闪屏，你们有遇到过么

**Comment by jkcaptain** [comment]
闪屏倒没遇到过，innerWidth不清楚。我测试过的几台手机，innerWidth都是正确的。

**Comment by airen** [comment]
请看 #98 的回答

**Comment by huanggm** [comment]
http://yukapril.com/2017/03/05/js-flexible.html
参考这里的解决方案-可以解决超出100宽度的问题

**Comment by jkcaptain** [comment]
谢谢分享。






------------------ 原始邮件 ------------------
发件人: "ThreeTree";<notifications@github.com>;
发送时间: 2017年11月30日(星期四) 晚上6:51
收件人: "amfe/lib-flexible"<lib-flexible@noreply.github.com>;
抄送: "JK"<1121655859@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [amfe/lib-flexible] 宽度使用10rem，在部分手机webview中未全屏。 (#84)




http://yukapril.com/2017/03/05/js-flexible.html
 参考这里的解决方案
