### ISSUE TITLE
当页面有两个section，字号会发生变化

### ISSUE THREAD

**Issue by gangxiaoya** [amfe/lib-flexible#89]
### HTML部分
![image](https://cloud.githubusercontent.com/assets/16329469/19436409/79e63bc2-94a2-11e6-9c69-6a0f43d6db2d.png)
### CSS部分
![image](https://cloud.githubusercontent.com/assets/16329469/19436491/f5c79f2e-94a2-11e6-96b3-7323d6a93e3c.png)

**Comment by mingelz** [comment]
页面触发了 [Font Boosting](https://github.com/amfe/article/issues/10)，加 `body * { max-height: 999rem; }` 可以解决。
