### ISSUE TITLE
lib.flexible接口使用

### ISSUE THREAD

**Issue by libofei2004** [amfe/lib-flexible#9]
请教一下，我想使用lib.flexible的接口，但在目前淘宝提供的flexible链接上http://g.tbcdn.cn/mtb/lib-flexible/0.2.3/??flexible_css.js,flexible.js ，代码和github上的不太一样，没有提供lib.flexible这些接口，请问这是为什么，如果想用这些接口怎么办呢？

**Comment by wintercn** [comment]
之前这边版本跟我们内部库版本不一样，做了一些同步，现在我们直接把源代码放出来了，应该已经是一样的了。
