### ISSUE TITLE
安卓 UC  rem不生效

### ISSUE THREAD

**Issue by okyping** [amfe/lib-flexible#90]
网上查是必须在页面加载完成之前设置html的font-size才生效，那就是这个代码必须放在head里面吗？对于第三方嵌入这个方向来说不太适用（不能控制用户将代码放到head里面），有好的方案吗

**Comment by tigerui** [comment]
改用内联方式写到顶部

**Comment by airen** [comment]
flexible.js必须加载在head里，不然会有问题。
