### ISSUE TITLE
Android高清屏手机上1px显示不是1px

### ISSUE THREAD

**Issue by nimiumiu** [amfe/lib-flexible#91]
在红米note3手机上，屏幕为高清屏，window.devicePixelRatio=2，dpr在Android手机中都为1，因此1px的线显示为2px，把dpr的iphone判断去掉后，1px显示正常，但是页面dom变大，页面宽度变宽可以左右滑动

**Comment by tigerui** [comment]
android 都是 1dpr

**Comment by airen** [comment]
在Android都重置了`dpr`的值为`1`。后面更新的版本，将解决这个问题。
