### ISSUE TITLE
flexible更改了<meta>导致苹果手机页面的二维码不能识别

### ISSUE THREAD

**Issue by PennyPP** [amfe/lib-flexible#93]
flexible更改了<meta>导致苹果手机页面的二维码不能识别，只有在缩放值设置为1的时候苹果手机才能识别二维码。如<meta content="width=device-width, initial-scale=1, maximum-scale=1.2, user-scalable=1" name="viewport" />

**Comment by hsj1606** [comment]
同样碰到这个问题，求解决方案

**Comment by kuangshu** [comment]
我也是这个问题,最后只有换用了固定meta和以前用的屏幕适配js代码解决.改源码的话,应该加一层判断微信的逻辑,让生成的meta 中scale为1

**Comment by didiself** [comment]
其实是苹果的识别位置下移了，可以用个hack的方法来解决。

将图片应用成bg，然后img opacity:0 ， img absolute 在盒子的上面，padding-bottom位移的距离，具体数值要调试一下；

这样视觉上位置不变，安卓的识别区域也不变，移动了苹果的识别区域。

**Comment by airen** [comment]
此问题和 #99 合并到一起

**Comment by Cybs** [comment]
像这样用hack的方法真的好么？ 还是应该想要从库内部方式来解决吧

**Comment by NicholasNC** [comment]
@Cybs 赞同，并且 hack 的方法也不是非常精致
