### ISSUE TITLE
想问一下用这个lib-flexible库的时候导航第三方组件库的一个ui组件样式都变得很小了~该怎么解决

### ISSUE THREAD

**Issue by ChangeZhang** [amfe/lib-flexible#95]
想问一下用这个lib-flexible库的时候导航第三方组件库的一个ui组件样式都变得很小了~该怎么解决
比如说用了mint-ui，但里面的组件都变得很小了，这种问题该怎么解决。

**Comment by Leega0** [comment]
同遇到了 这个问题，楼下有人说设置dpr为1.

**Comment by airen** [comment]
#80
