### ISSUE TITLE
webpack 打包的问题

### ISSUE THREAD

**Issue by limaoxuan** [amfe/lib-flexible#96]
webpack打包 报错
ERROR in ../~/.0.26.0@css-loader!./styles/index.css
Module build failed: Unknown word (4:31)

  2 |   /*width: 1rem;*/
  3 |   /*height: 0.4rem;*/
> 4 |   font-size: 12px !important; // 默认写上dpr为1的fontSize
    |                               ^
  5 | }
  6 |
  7 | [data-dpr="2"] .footer-size {

**Comment by airen** [comment]
这个可以查一下Webpack相关的打包机制。
