### ISSUE TITLE
魅族pro6中UC浏览器没有全屏展示的问题

### ISSUE THREAD

**Issue by luchanan** [amfe/lib-flexible#98]
UA:Mozilla/5.0 (Linux; U; Android 6.0; zh-CN; PRO 6 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 UCBrowser/11.2.1.888 Mobile Safari/537.36
meta标签
initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no
css
body 10rem
在body标签签名打印出来
alert($("body").width())//298
alert($(".banner_box").width());//299
alert($(window).width());//360
alert(window.devicePixelRatio)//3
alert(document.documentElement.getBoundingClientRect().width)//360
alert(lib.flexible.rem)//36
照理来说html font-size是36，body为10rem ,计算出来是36*10=360才对啊怎么是298呢？
现在的h5的淘宝主页也是不全屏的，大家可以看看

**Comment by lin-hun** [comment]
+1 魅族note 也是

**Comment by airen** [comment]
建议外部容器不要设置`witd:10rem`，可以考虑使用100%。因为在Android设备下，做了一个宽度的限制处理`540px`。如果设备超过`540px`的宽度，那么`10rem`就会造成两边留白居中显示。这个时候你只要避开`10rem`或者将重置一下这个小值，就可以解决这类现象。

**Comment by luchanan** [comment]
1、虽然说body改了100%可以全屏，但是如果body里面元素用的是rem宽高单位的话，比例就有问题了，也不是根据整个屏幕铺满的，或者里面元素也使用百分比解决吧。
2、另外这部机器docEl.getBoundingClientRect().width得出来是360，所以refreshRem()方法里面的if为true是不会执行了，设备就不会超过你上面说的540，留白应该不是这个原因。
3、这部机器用微信浏览器就是全屏的，怀疑是不是UC对这个rem解析有问题

**Comment by lin-hun** [comment]
这个只有uc出现么

**Comment by luchanan** [comment]
@lin-hun 是的，上面有UA

**Comment by lin-hun** [comment]
我觉得是uc的坑，之前有一次app调webview，不管怎么改，在魅族note上设置rem宽度时会按94%计算，后发现是默认webview的问题。

**Comment by luchanan** [comment]
@lin-hun  那解决方法是？

**Comment by lin-hun** [comment]
设置webview setTextZoom(100)
在[stackoverflow](http://stackoverflow.com/questions/29816804/fixed-text-size-in-webview-android-lollipop)看到的

**Comment by luchanan** [comment]
@lin-hun 你这是在app设置的啊？问题这UC是别人的~~
