### ISSUE TITLE
关于微信中长按扫描二维码的问题

### ISSUE THREAD

**Issue by kuangshu** [amfe/lib-flexible#99]
我引用了flexible来做适配,但是在微信环境下页面中有个二维码,在IOS中很难弹出 "识别图中二维码",只有偶尔按住某块区域的时候才会出现,我自己查了些资料,有说好像是meta标签中viewport的scale要大于1,我自己换用固定 viewport中的 scale为1并且换用以前做适配的js代码后,问题就消失了.不知道作者做过这方面的测试没有,反正我这里flexible在微信扫码的场景下有点问题.我也在检查我自己的代码问题,不过还是提一下问题看有没有遇到类似情况的同学,并且是怎么解决的

**Comment by didiself** [comment]
其实是苹果的识别位置下移了，可以用个hack的方法来解决。

将图片应用成bg，然后img opacity:0 ， img absolute 在盒子的上面，padding-bottom位移的距离，具体数值要调试一下；

这样视觉上位置不变，安卓的识别区域也不变，移动了苹果的识别区域。

// 其实前面有人提问了。

**Comment by kuangshu** [comment]
我重新试了下给父盒子加背景,img设opacity:0，添加padding-bottom后，也只有右测能识别。
通过设置了right让图片左移后，图片区域都可以识别了，然而手边没有安卓机，不知道改成这样了之后安卓是正常的不。
